### ISSUE TITLE
Certbot can not startup

### ISSUE THREAD

**Issue by heimuya** [laradock/laradock#1012]
### Info:
- Docker version (`Docker version 17.03.1-ce, build c6d412e`): 
- Laradock commit (`05f8166bef6c3bdf769a71e3fd83368bd68722c3`): 
- System info (Linux): 
- System info disto/version:  Ubuntu 16.04.2 LTS

### Issue:
when use `docker-compose up -d nginx certbot` to start the nginx and certbot container,  the result is nginx container running, while certbot container's state is Exit. 

![image](https://user-images.githubusercontent.com/5266605/27016684-2938cab4-4f55-11e7-8d2c-fdb0633d6bea.png)

what's more, I have replaced the email and domain content with my own infomation at  certbot config section in dock-compose.yml file.

Is there any wrong? Hope someone can help. Thanks.

**Comment by vitoo** [comment]
What's the output of : `docker-compose logs certbot`

**Comment by heimuya** [comment]
@vitoo the output is 
```
certbot_1              | Requested domain "edc.easygreat.net" is not a FQDN
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/"edc.easygreat.net"/cert1.pem': No such file or directory
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/"edc.easygreat.net"/privkey1.pem': No such file or directory
```
but I find the domain is ok. Thanks for your reply.

**Comment by vitoo** [comment]
Looks like certbot doesnt want your domain

**Comment by winfried-van-loon** [comment]
I'm not sure if it's part (or the cause of) the problem, however those `"` symbols look strange there. Could it be the cause of the issue?

**Comment by kirtangajjar** [comment]
@winfried-van-loon @heimuya Excatly, I had the same problem. Turns out, you have to change 
`CN="fake.domain.com"` to `CN=fake.domain.com`

**Comment by JIFT** [comment]
Not working for me. 

Failed authorization procedure. letterswar.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://xxxxx.com/.well-known/acme-challenge/Gnq1fgpCJFYkH2cAHABN1l1i0cBIDS45LQ3wLVkXXXX: "<html>
certbot_1       | <head><title>404 Not Found</title></head>
certbot_1       | <body bgcolor="white">
certbot_1       | <center><h1>404 Not Found</h1></center>
certbot_1       | <hr><center>"
certbot_1       | IMPORTANT NOTES:
certbot_1       |  - If you lose your account credentials, you can recover through
certbot_1       |    e-mails sent to xxxx@gmail.com.
certbot_1       |  - The following errors were reported by the server:

**Comment by doghap** [comment]
@JIFT  put this code into you nginx config: 
```   
 location /.well-known/acme-challenge/ {
        root /var/www/laradock/certbot/letsencrypt/;
        log_not_found off;
    }
``` 
letsencript generate `.well-known/acme-challenge/xxxxxxxxxx` files in to `/laradock/certbot/letsencrypt` folder. you can find your certs in `laradock/data/certbot/certs/`

**Comment by heshuo13** [comment]
Not working for me.     

404 Not Found
help

**Comment by heshuo13** [comment]
The following errors were reported by the server:

   Domain: *****
   Type:   unauthorized
   Detail: Invalid response from http://******/.well-
   known/acme-challenge/6uE4HCVIZ7xN4Y4PH-wI1bOYIAbMu8qc1Gejxbp62CA:
   "<html>
   <head><title>404 Not Found</title></head>
   <body bgcolor="white">
   <center><h1>404 Not Found</h1></center>
   <hr><center>"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.

**Comment by JIFT** [comment]
The error was fixed when I add the certs volume to the docker-compose.yml
applications:
        image: tianon/true
        volumes:
            - ./data/certbot/certs/:/var/certs

**Comment by heshuo13** [comment]
@JIFT  i want to know you config, nginx and certbot

**Comment by Trexology** [comment]
@Ishodnikov Hi, i tried adding the

volumes:
- ./data/certbot/certs/:/var/certs
- ./certbot/letsencrypt/:/var/www/letsencrypt

under my apache2 section but somehow it does not work
```
    apache2:
      build:
        context: ./apache2
        args:
          - PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}
          - PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}
          - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
        - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt
```
