### ISSUE TITLE
Pointing 9000 to php-fpm with xdebug enabled

### ISSUE THREAD

**Issue by LarryEitel** [LaraDock/laradock#102]
I can slugging through configuring phpstorm for remote debugging. I have a SSL access to remote workspace. I added to workspace/Dockerfile:

```
RUN rm -f /etc/service/sshd/down

ADD id_rsa_vm /root/.ssh
ADD id_rsa_vm.pub /root/.ssh
RUN touch /root/.ssh/authorized_keys
RUN cat /root/.ssh/id_rsa_vm.pub >> /root/.ssh/authorized_keys
```

I added to php-fpm/Dockerfile-70:

```
RUN echo "xdebug.remote_enable=1\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_handler=dbgp\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_mode=req\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_host=<whatismyip>\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_port=9000\n" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# for confirmation
RUN cat /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN php -i | grep xdebug.remote
```
QUESTION...
I need to point to PHP running in the php-fpm container which now has xdebug enabled and verified and able to connect to by listening phpstorm (telephone debug icon on).
When I point to the IP of the workspace, it sees the PHP in THAT container, not the php-fpm container. Do I have to set up SSH access to that container and point to it rather than workspace container IP?

Another option is to add xdebug to the workspace container?

**Comment by nemanjam** [comment]
See docker-compose.yml and php-fpm folder in my_laradock branch of my fork, you have working xdebug there https://github.com/nemanjam/laradock/tree/my_laradock

**Comment by LarryEitel** [comment]
Thank you! Your example helped me to FINALLY initiate a debug session.

I added:
```    
php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-70
        volumes_from:
            - application
        volumes:
            - ./logs/php-fpm/:/tmp/xdebug_log
        expose:
            - "9000"
        ports:
            - "9001:9001"
        links:
            - workspace
        environment:
            XDEBUG_CONFIG: "remote_host=<my external IP>"
            PHP_IDE_CONFIG: "serverName=docker"
```
I also found a way to setup remote debug over SSL. Late now. Will share my docker-compose soon.
