### ISSUE TITLE
The project folder do not map to workspace

### ISSUE THREAD

**Issue by ralphxlx** [laradock/laradock#1026]
### Info:
- Docker version (`$ docker --version`): 17.05.0-ce
- Laradock commit (`$ git rev-parse HEAD`): 1bba93042d5173f905e4f9d0cf2e6a2776282af8
- System info (Mac, PC, Linux): PC 、Mac
- System info disto/version: Windows 10 Home、MacOS Sierra 10.12.5

##### What seems to be going wrong?
The project folder do not map to workspace. And i `exec`  workspace bash, the `/var/www/demo` is empty.
_____

##### What should be happening instead?
 The `/var/www/demo` has project files and i can access the http://localhost.
_____

### Relevant Code:
```
### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ../demo/:/var/www/demo
```
