### ISSUE TITLE
could not connect to server: Connection refused

### ISSUE THREAD

**Issue by rogyvoje** [laradock/laradock#1061]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): f258b38a18dc915f6eb89ad57dd7bd48f2960a2d
- System info (Mac, PC, Linux): PC
- System info disto/version: Windows 10

##### What seems to be going wrong?
could not connect to server: Connection refused
        Is the server running on host "postgres" (172.20.0.2) and accepting
        TCP/IP connections on port 5433?
_____

##### What should be happening instead?
I intentionally set port to be 5433, and every time I try to execute `php artisan migrate`
I get this error, so the postgres is running but why it refuses to connect?
I tried with Navicat to connect and it works perfectly fine. In my .env file I set:
```
DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5433
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret
```
_____

##### How might we be able to reproduce the error?
- inside `laradock/.env` set postgres port to be 5433
- set your .env file `DB_HOST=5433`
- `docker-compose up -d nginx postgres`
- `docker-compose exec workspace bash`
- inside container `php artisan migrate`
error shows up

**Comment by LadislavMarkus** [comment]
@rogyvoje  If you are using Windows you should set port to 5432 in your project .env file, your postgres container is probably set to expose port 5432 despite your using port 5433 :
```
DB_CONNECTION=pgsql
DB_HOST=postgres
**DB_PORT=5432**
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret
```

Also if you are using latest laradock be sure to configure PostgreSQL Container in docker-compose.yml file, this config worked for me:
```
### PostgreSQL Container ####################################

    postgres:
      build: ./postgres
      volumes:
###        - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
        - data:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend
```
and
```
data:
    driver: "local"
```

**Comment by rogyvoje** [comment]
Yeah, this worked for me, but I don't understand why I need to set port 5432 if inside `laradock/.env` file I strictly said 5433...
And also docker-compose.yml is not really configured to work with postgres and docker on windows, as I can see...
Is there going to be some kind of a fix for this problem?

**Comment by chrispaynter** [comment]
I have the same "problem" @rogyvoje in a different situation using a  .NET Core app, but I think the findings help support @LadislavMarkus's point.

Here's the excerpt from my Docker file for the postgres container:
```

version: '3'
services:
  app.tests.postgres:
    image: app.tests.postgres
    restart: always
    ports:
      - 5433:5432
app.tests:
    build: 
      context: ../../src/App
    image: app.tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=User ID=sured;Password=sured;Host=postgres;Port=5432;Database=sured;Pooling=true;
        ports:
           - "5002:5000"
    links:
      - app.tests.postgres:postgres
    depends_on:
        - app.tests.postgres
```

What I am finding, as you have done, is that by changing my connection string port to 5432, the application is able to connect to `app.tests.postgres` successfully within the internal Docker network. If that connection string was for Port 5433 then the connection would be refused.

Now, on my local machine (outside the context of Docker), if I spin up PgAdmin, I am able to connect to `app.tests.postgres` directly by connecting to localhost:5433 with the same credentials, however, localhost:5432 will not connect.

My deduction is that when `app.tests` container is linked to the `app.tests.postgres` container, the connection port is the same one that is being exposed by the Docker file that the image was made from. In my case, I'm using the official postgres image as my base, which exposes 5432. In the case of the ports being set on `sured.tests.postgres`, they are only being exposed for connections outside of the internal docker network being created.

At least this is what I can tell without spending more time I don't have at the moment to clarify.

Hoping to come across official documentation on this when I get a chance.
