### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by nWidart** [laradock/laradock#107]
Hello,

I wanted to give LaraDock a try with docker getting into open beta.

I followed the steps to use it inside a laravel app.
- `git submodule add https://github.com/LaraDock/laradock.git`
- `docker-machine create -d virtualbox default`
- `docker-machine start default`
- `eval $(docker-machine env)`
- Edited .env with `DB_HOST=192.168.99.100`
- `docker-compose up -d  nginx mysql redis workspace`

Now when browsing to the docker ip `192.168.99.100` I'm getting a browser error

```
This site can’t be reached

192.168.99.100 refused to connect.
```

(ran the chmod of storage/ & bootstrap/cache/ folders)

Did I miss something ?

Thank you,

**Comment by appleboy** [comment]
```
    workspace:
        build: ./workspace
        volumes_from:
            - application
        tty: true
        links:
            - mysql
```

link `mysql` to your workspace container and change `DB_HOST` to `mysql` value.

**Comment by nWidart** [comment]
I'm assuming you're talking about the `docker-compose.yml` file.

It already contained the following

```
    workspace:
        build: ./workspace
        volumes_from:
            - application
        tty: true
```

So I added the links-mysql part and ran a `docker-compose build`. 

I still see the "The site can't be reached" error.

I'm not sure what you mean by 

> link mysql to your workspace container and change DB_HOST to mysql value.

Instead of using an IP, I should use the string `mysql` ? 


Thanks
