### ISSUE TITLE
Add Laravel Horizon service

### ISSUE THREAD

**Issue by hackel** [laradock/laradock#1070]
So, the code was only released today, but I figured it would be good to get the ball rolling.  I'm really excited about this project!

As a quick hack, I've extended the laradock-workspace container to get it working like so:
```yml
    laravel-horizon:
      build:
        context: ./workspace
        args:
          - PUID=${WORKSPACE_PUID}
          - PGID=${WORKSPACE_PGID}
          - TZ=${WORKSPACE_TIMEZONE}
        dockerfile: "Dockerfile-${PHP_VERSION}"
      volumes_from:
        - applications
      networks:
        - backend
      user: laradock
      command: php /var/www/artisan horizon
```

This is rather inefficient, pulling in the full Ubuntu image of workspace, but if you just want to start playing with it, it's a great quick-and-dirty solution.  Eventually it will need to use supervisor or some kind of process monitor.  I considered extending the php-worker service, but unfortunately nielsvdoorn/laravel-supervisor doesn't support configuring supervisor with environment variables and would require a separate Dockerfile and supervisord.conf.

**Comment by Shadow2004** [comment]
Has any one implemented this with supervisor yet?

**Comment by codeitlikemiley** [comment]
im currently looking for a way to use it on my project also

**Comment by princeton255** [comment]
I have managed to get horizon working with the laradock php-worker service

#### 1. Changed the command in `/laradock/php-worker/supervisord.conf` 

from
`command=php /var/www/artisan queue:work --sleep=3 --tries=3 --daemon`
to 
`command=php /var/www/artisan horizon`

#### 2. And added `pcntl` extension which is required by redis driver to the php-worker.

In files `/laradock/php-worker/Dockerfile-70 `and `/laradock/php-worker/Dockerfile-71`

Changed line
`RUN docker-php-ext-install mysqli mbstring pdo pdo_mysql mcrypt tokenizer xml`
to 
`RUN docker-php-ext-install mysqli mbstring pdo pdo_mysql mcrypt tokenizer xm pcntl`

**Comment by codeitlikemiley** [comment]
i tried just to configure the php-worker , but i can seem to make it work....
do i need to do the step below   in addition to configuring php-worker?

@princeton255 

```
  laravel-horizon:
      build:
        context: ./workspace
        args:
          - PUID=${WORKSPACE_PUID}
          - PGID=${WORKSPACE_PGID}
          - TZ=${WORKSPACE_TIMEZONE}
        dockerfile: "Dockerfile-${PHP_VERSION}"
      volumes_from:
        - applications
      networks:
        - backend
      user: laradock
      command: php /var/www/artisan horizon

```
