### ISSUE TITLE
Feature request: Add sentry containers.

### ISSUE THREAD

**Issue by exfriend** [laradock/laradock#1096]
Hey guys! Wouldn't it be nice to have a bug reporting system in the box?
Here is what I am using at the moment:

```
### Sentry Container ####################################

    sentry:
      image: sentry:latest
      depends_on:
       - redis
       - postgres
      links:
       - redis
       - postgres
      ports:
       - 9000:9000
      environment:
       - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
       - SENTRY_REDIS_HOST=redis
       - SENTRY_POSTGRES_HOST=postgres
       - SENTRY_DB_USER=${POSTGRES_USER}
       - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend
        - frontend

    sentry_celery_beat:
      image: sentry:latest
      depends_on:
       - redis
       - postgres
      command: "sentry run cron"
      environment:
       - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
       - SENTRY_REDIS_HOST=redis
       - SENTRY_POSTGRES_HOST=postgres
       - SENTRY_DB_USER=${POSTGRES_USER}
       - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend
        - frontend

    sentry_celery_worker:
      image: sentry:latest
      depends_on:
       - redis
       - postgres
      command: "sentry run worker"
      environment:
       - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
       - SENTRY_REDIS_HOST=redis
       - SENTRY_POSTGRES_HOST=postgres
       - SENTRY_DB_USER=${POSTGRES_USER}
       - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend
        - frontend
```
Set up:
`docker-compose exec sentry bash`
`sentry upgrade`
