### ISSUE TITLE
Reference nginx hostname from php-fpm

### ISSUE THREAD

**Issue by feribg** [laradock/laradock#1119]
### Info:
- Docker version (`all`): 
- Laradock commit (`all`): 
- System info (Mac, PC, Linux): all
- System info disto/version: 

### Issue:

Nginx container depends on php-fpm which doesnt allow to use a custom hostname and reference it within PHP.
_____

### Expected behavior:
Should be able to call ```<?php some_func_get_url('laradock.local.nginx.host') ?>```

### Reproduce:

_____

### Relevant Code:
Possible solution that works fine is to make an alias as described below with the new hostname as the nginx host, then add both php-fpm and nginx on the new network, avoiding circular container dependencies.
https://medium.com/@yani/two-way-link-with-docker-compose-8e774887be41

```
    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM=php-fpm
      volumes_from:
          - applications
      volumes:
          - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
          - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
          - "${NGINX_HOST_HTTP_PORT}:80"
          - "${NGINX_HOST_HTTPS_PORT}:443"
      extra_hosts:
          - "your.nginx.local.hostname:127.0.0.1"    
      depends_on:
          - php-fpm
      networks:
        main:
          aliases:
            - "${NGINX_HOSTNAME}"
```
