### ISSUE TITLE
caddy cert and laravel-echo-server

### ISSUE THREAD

**Issue by nguyenhaiphan** [laradock/laradock#1124]
I intend to use laravel-echo-server in https mode with Caddy, where should I config to share the Caddy signed certificate to laravel-echo-server ?

Thank in advance,

**Comment by exfriend** [comment]
Use the shared volume (you may adjust the volume and symilks to use particular certs):
`
    caddy:
      build: ./caddy
      volumes_from:
        - applications
      volumes:
        - ${CADDY_CUSTOM_CADDYFILE}:/etc/Caddyfile
        - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
        - ${DATA_SAVE_PATH}:/root/.caddy
        - ../storage/certs/letsencrypt:/root/.caddy/acme/acme-v01.api.letsencrypt.org/sites/
`
Then mount the same storage folder to Laravel Echo Server:
`
### Laravel Echo Server #######################################
    laravel-echo-server:
      build:
        context: ./laravel-echo-server
      volumes:
        - ./laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
        - ${STORAGE}:/storage
`

Using config like this:
`{
  "appKey": "base64:iScEWLNRyVNXoMDbNmo/U/8GjSztcbpsyReYy/Nru8I=",
  "authHost": "http://caddy",
  "authEndpoint": "/broadcasting/auth",
  "clients": [
    {
      "appId": "TEST",
      "key": "AAAAABBBBBBCCCCCDDDDD"
    }
  ],
  "database": "redis",
  "databaseConfig": {
    "redis": {
      "port": "6379",
      "host": "redis"
    },
    "sqlite": {
      "databasePath": "/database/laravel-echo-server.sqlite"
    }
  },
  "devMode": true,
  "host": null,
  "port": "6001",
  "protocol": "http",
  "socketio": {},
  "sslCertPath": "/storage/certs/cert.pem",
  "sslKeyPath": "/storage/certs/key.pem"
}
`

**Comment by nguyenhaiphan** [comment]
I figured it out.

Just try to shares the volume of caddy to laravel-echo-server in docker-composer.yml
```yaml
### Laravel Echo Server #######################################
    laravel-echo-server:
      build:
        context: ./laravel-echo-server
      volumes_from:
        - caddy:ro
#the shared volume will be mounted to /root/caddy, the 'ro' will block the writable permission from laravel-echo-server
      volumes: ...
```

Then from the laravel-echo-server.json, I can tell it to fetch ssl such as:
```json
	"sslCertPath": "/root/.caddy/acme/acme-v01.api.letsencrypt.org/sites/<caddy-registered.domain.name>/<caddy-registered.domain.name>.crt",
	"sslKeyPath": "/root/.caddy/acme/acme-v01.api.letsencrypt.org/sites/<caddy-registered.domain.name>/<caddy-registered.domain.name>.key"
```

**Comment by codeitlikemiley** [comment]
can you share us the whole step you did?

**Comment by nguyenhaiphan** [comment]
@codeitlikemiley Please tell me what exactly do you want to do? The problem I proposed here is different with another issue that I also proposed. You can private message me via skype pnghai179 and I can see if I can help your case.

Regards,

**Comment by codeitlikemiley** [comment]
i just need to user laravel echo server with ssl using either caddy or nginx....

**Comment by nguyenhaiphan** [comment]
How many site do you have? The solution I and @exfriend proposed is used for single site setup. 

The key is you should share the source of truth (here is the caddy volumes that Caddy itself signed cert and key for your domain) so that the laravel-echo-server container can check that volume from its own container.

**Comment by cre8** [comment]
Instead of sharing the volume you can get the needed files from the `DATA_SAVE_PATH` folder (i used `../tmp`). If you generated your certs with caddy they will be stored in `../tmp/acme/acme-v01.api.letsencrypt.org/sites/<your-domain>/`
you can mount the both files (crt and key) as volumes into the laravel-echo-server:

```
laravel-echo-server:
      build:
        context: ./laravel-echo-server
      volumes:
        - ./laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
        - ../tmp/acme/acme-v01.api.letsencrypt.org/sites/example.com.crt/:example.com.crt:ro
        - ../tmp/acme/acme-v01.api.letsencrypt.org/sites/example.com.key/:example.com.key:ro
```
