### ISSUE TITLE
Help deploying to ECS / Elasticbeanstalk

### ISSUE THREAD

**Issue by NiluK** [laradock/laradock#1131]
### Info:
- Docker version (`$ docker --version`):  Docker version 17.06.2-ce, build cec0b72
- Laradock commit (`$ git rev-parse HEAD`): 
- System info (Mac, PC, Linux): Mac OS X for Dev, Linux for Production 
- System info disto/version: 

### Issue:

Hi all, I'm looking for a good tutorial for a way to deploy the Laradock application containers into ECS or Elastic Beanstalk. The tutorials I've seen on the web were excellent for small custom made Dockerfiles, but I haven't been able to find any that help with deploying an application on the scale of Laradock. 

I can get Laradock up and running on a single EC2 instance fine, but when creating Auto Scaling Groups based on an ELB, this will not work as I'd have to login into each of the EC2 instances and then run the composer and artisan commands etc. 

Is there a way to do this with Laradock, or what is the recommended way to deploy Laradock to production in ECS or ELB.

I should be able to login to a main load-balancer or something similar and run my commands to seed the database etc without having to do this for each new instance that would be created and then destroyed in an AutoScaling group. 

### Relevant Code: 

Docker Compose File

```
version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
          - ${APPLICATION}:/var/www

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
                - INSTALL_SOAP=${WORKSPACE_INSTALL_SOAP}
                - INSTALL_MONGO=${WORKSPACE_INSTALL_MONGO}
                - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
                - INSTALL_YARN=${WORKSPACE_INSTALL_YARN}
                - INSTALL_DRUSH=${WORKSPACE_INSTALL_DRUSH}
                - INSTALL_AEROSPIKE_EXTENSION=${WORKSPACE_INSTALL_AEROSPIKE_EXTENSION}
                - INSTALL_V8JS_EXTENSION=${WORKSPACE_INSTALL_INSTALL_V8JS_EXTENSION}
                - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
                - INSTALL_WORKSPACE_SSH=${WORKSPACE_INSTALL_WORKSPACE_SSH}
                - INSTALL_LARAVEL_ENVOY=${WORKSPACE_INSTALL_LARAVEL_ENVOY}
                - INSTALL_DEPLOYER=${WORKSPACE_INSTALL_LARAVEL_ENVOY}
                - INSTALL_LINUXBREW=${WORKSPACE_INSTALL_LARAVEL_ENVOY}
                - INSTALL_MC=${WORKSPACE_INSTALL_MC}
                - PUID=${WORKSPACE_PUID}
                - PGID=${WORKSPACE_PGID}
                - NODE_VERSION=${WORKSPACE_NODE_VERSION}
                - YARN_VERSION=${WORKSPACE_YARN_VERSION}
                - TZ=${WORKSPACE_TIMEZONE}
            dockerfile: "Dockerfile-71"
        volumes_from:
            - applications
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        ports:
           - "${WORKSPACE_SSH_PORT}:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
                - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
                - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
                - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
                - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
                - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
                - INSTALL_AEROSPIKE_EXTENSION=${PHP_FPM_INSTALL_AEROSPIKE_EXTENSION}
                - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
                - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
                - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
            dockerfile: ${PHP_FPM_DOCKER_FILE}
        volumes_from:
            - applications
        expose:
            - "9000"
        depends_on:
            - workspace
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        environment:
            - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - applications
        volumes:
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
        environment:
            - VIRTUAL_HOST=gamurs.app

### MySQL Container #########################################

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"

### Memcached Container #####################################

    memcached:
        build: ./memcached
        volumes:
            - memcached:/var/lib/memcached
        ports:
            - "${MEMCACHED_HOST_PORT}:11211"
        depends_on:
            - php-fpm
#### ElasticSearch Container #################################
#
    elasticsearch:
        build: ./elasticsearch
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
            - elasticsearch-plugins:/usr/share/elasticsearch/plugins
        ports:
            - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
            - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
        depends_on:
            - php-fpm

### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
    memcached:
        driver: "local"
    elasticsearch-data:
        driver: "local"
    elasticsearch-plugins:
        driver: "local"

```

The MySQL, ElasticSearch and Memcached containers will eventually be replace with RDS, AWS ElasticSearch and AWS ElasticCache but in the meantime, I'd like to know how to get the application up and running on ECS or Elastic Beanstalk. I can't seem to find decent tutorials for this unfortunately, so any help would be much appreciated.

Thanks.
