### ISSUE TITLE
Xdebug: don't work

### ISSUE THREAD

**Issue by vudev** [laradock/laradock#1193]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): 903c77421c8433619a7d6cf79cec68e24ac99266
- System info (Mac, PC, Linux): Mac Os high sierra, laradock, phpstorm, xdebug helper
- System info disto/version: Mac Os high sierra

### Issue:

Xdebug don't work.
In phpstorm show:
Waiting for incoming connection with ide key 'PHPSTORM'

in docker-composer.yml
workspace:
      build:
        context: ./workspace
        args:
          - INSTALL_XDEBUG=true
php-fpm:
      build:
        context: ./php-fpm
        args:
          - INSTALL_XDEBUG=true

xdebug.ini
xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.remote_connect_back=0
xdebug.cli_color=1
xdebug.profiler_enable=0
xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.remote_port=9000
xdebug.remote_host=dockerhost
xdebug.idekey=PHPSTORM

![screen shot 2017-10-16 at 4 37 36 pm](https://user-images.githubusercontent.com/20655326/31605402-5e82d2ac-b290-11e7-8dfb-d05150d7e87f.png)
![screen shot 2017-10-16 at 4 38 07 pm](https://user-images.githubusercontent.com/20655326/31605442-6b41ab44-b290-11e7-9b4e-2b826b955037.png)
![screen shot 2017-10-16 at 4 40 00 pm](https://user-images.githubusercontent.com/20655326/31605586-c8103e76-b290-11e7-9896-e87b574de9bf.png)
![screen shot 2017-10-16 at 4 40 20 pm](https://user-images.githubusercontent.com/20655326/31605588-c842fb54-b290-11e7-8705-a0349a052295.png)
![screen shot 2017-10-16 at 4 40 29 pm](https://user-images.githubusercontent.com/20655326/31605589-c876975c-b290-11e7-92a7-8ac7341d47e6.png)
![screen shot 2017-10-16 at 4 39 27 pm](https://user-images.githubusercontent.com/20655326/31605591-c8b531b0-b290-11e7-80f7-8ee38a31c563.png)
![screen shot 2017-10-16 at 4 39 38 pm](https://user-images.githubusercontent.com/20655326/31605592-c8e8bdd2-b290-11e7-8aeb-c24dc6d9f015.png)
![screen shot 2017-10-16 at 4 39 44 pm](https://user-images.githubusercontent.com/20655326/31605594-c91d903e-b290-11e7-90d7-4e1ee6e9b5a5.png)

**Comment by vudev** [comment]
I think it conflict mac os high sierra

**Comment by rodion-arr** [comment]
OK, seems I solved the issue.

php-fpm section of **docker-compose.yml** is standard, no changes
```
php-fpm:
      build:
        context: ./php-fpm
        args:
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
          - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE}
          - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
          - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO}
          - INSTALL_MSSQL=${PHP_FPM_INSTALL_MSSQL}
          - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
          - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
          - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
          - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
          - INSTALL_AEROSPIKE=${PHP_FPM_INSTALL_AEROSPIKE}
          - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
          - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
          - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
          - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
          - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
          - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
        dockerfile: "Dockerfile-${PHP_VERSION}"
      volumes_from:
        - applications
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      networks:
        - backend
```

**php.ini**
```
xdebug.remote_autostart=1
xdebug.remote_enable=1
xdebug.remote_connect_back=0
xdebug.cli_color=1
xdebug.profiler_enable=0
xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.remote_port=9000
xdebug.remote_host=YOUR_LOCAL_IP_ADDRESS
xdebug.idekey=PHPSTORM
```
Where `YOUR_LOCAL_IP_ADDRESS` is the value from `ifconfig` command. In my case it was in `en0` section in `inet` row
```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ... 
	inet6 ... prefixlen 64 secured scopeid 0x5 
	inet HERE_IS_LOCAL_IP netmask 0xffffff00 broadcast ....
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```
PhpStorm settings:
![1](https://user-images.githubusercontent.com/5843270/32005900-1e77e042-b9ae-11e7-9150-9538fbf6488a.png)
![2](https://user-images.githubusercontent.com/5843270/32005904-1ee3be7a-b9ae-11e7-8056-d3ee55f6e8c6.png)
![3](https://user-images.githubusercontent.com/5843270/32005906-1f4ce418-b9ae-11e7-85dd-82241ce423fc.png)
![4](https://user-images.githubusercontent.com/5843270/32005908-1f8a042e-b9ae-11e7-9a4e-890179eabcdd.png)
![5](https://user-images.githubusercontent.com/5843270/32005910-200da004-b9ae-11e7-96dd-1e73e99ac91f.png)
![6](https://user-images.githubusercontent.com/5843270/32005912-20a1f3d0-b9ae-11e7-8d7a-fa1507f7bdb3.png)

Good luck!
