### ISSUE TITLE
PHP Worker: Documentation Outdated

### ISSUE THREAD

**Issue by FroeMic** [laradock/laradock#1218]
### Issue:
The documentation is outdated with regards to how to  **Run Laravel Queue Worker**.
_____

### Expected behavior:
Update with the working code from this repository.

https://github.com/laradock/laradock/blob/c2c30bfd0f278f6978a48dc62cf3ee063c9f3efa/docker-compose.yml#L109

```
### PHP Worker Container #####################################

    php-worker:
      build:
        context: ./php-worker
        dockerfile: "Dockerfile-${PHP_VERSION}"
      volumes_from:
        - applications
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      networks:
        - backend
```
_____

### Reproduce:
Follow the instructions here: http://laradock.io/documentation/#run-laravel-queue-worker
It won't work.
_____
