### ISSUE TITLE
Docker-sync integration does not work this way - it has no effect right now

### ISSUE THREAD

**Issue by EugenMayer** [laradock/laradock#1226]
Due to 

- https://github.com/laradock/laradock/blob/master/docker-compose.yml#L10 in the docker-compose.yml

this will have no effect

https://github.com/laradock/laradock/blob/master/docker-compose.sync.yml#L10

This is just a normal limitation by docker-compose, you cannot override volume mounts.

Your conceptual issue is, that docker-compose.yml is actually already docker-compose-dev.yml for all systems like linux ( direct mount has no effect ). There is no production docker-compose.yml and thus not file without a mount.

Best-practise:

- cp docker-compose.yml to docker-compose-dev.yml and 
-  remove anything from docker-compose-dev.yml which does not change for development, this means most probably all you will leave in docker-cmpose-dev.yml will be

```    
    version: "2"
    
    services:
      applications:
        volumes:
          - ${APPLICATION}:/var/www
        ports:
          - "${WORKSPACE_SSH_PORT}:22"
      fpm:
        expose:
          - "9000"
```

This is all you have in docker-compose-dev.yml, you docker-compose.yml will be all it has been right now, but without the values above, so remove volumes ports in application(ssh) and expose - remove anything you have in -dev.yml

Now create a .env file and put that inside

    COMPOSE_FILE=docker-compose.yml:docker-compose-dev.yml

This will ensure, that anybody using `docker-compose up` will still start the dev stack automatically as he would do

`docker-compose -f docker-compose.yml -f docker-compose-dev.yml`

but with the same convinience you have right now, just do

`docker-compose up`

After doing that, docker-sync will perform as expected and #353 will be fixed

**Comment by jeff-h** [comment]
I also had to track down and find out why docker-sync wasn't working for me, and ended up commenting out the referenced line 10. Sorry, I should have contributed some documentation change regarding this, but I'm pretty new to docker and tend to be quite unsure that my changes are correct.

I really like this idea for another reason, which is related to using Laradock in production. There really are very few parts of the current `docker-compose.yml` that have to be different between a production and a development version. Volumes are the main thing that cannot be overridden by a second docker-compose file (eg a `docker-compose-prod.yml`), so separating certain volume config (and anything else like it) into a `-dev` and `-production` version would be great, and not cause any excess maintainability issues for the project, because it would not result in any code redundancy.

Then, all we need is an `.env` and an `.env.prod` file which each specify how the various docker-compose configs should behave in their referenced environment (eg include `xdebug` in dev but not in prod).

**Comment by jeff-h** [comment]
@EugenMayer — I have created a PR from your suggestions above, partly because I really need it! :)

However, in my proposed `docker-compose.dev.yml` I only included the volume mapping. Could you explain why you propose the `applications - ports` and the `fpm` sections?

**Comment by EugenMayer** [comment]
@jeff-h because you usually do not expose DB ports or similar in production, so all the internal ports be it 5005, 8080 and not the nginx/passproxy port only - its not a key thing, the volumes are far more important - its just a conceptual thing

**Comment by scaule** [comment]
@EugenMayer this issue is ok and can be closed ?

**Comment by EugenMayer** [comment]
looks goood for me, thanks for the effort @scaule

**Comment by EugenMayer** [comment]
By the way https://github.com/EugenMayer/docker-sync/issues/507  https://github.com/docker/compose/pull/5223 is part of the newest docker-compose release nowdays

**Comment by scaule** [comment]
Great news for volume override  :) !
@EugenMayer Could you close it because i don't have the right to do it ? thx

**Comment by coderars** [comment]
Is the current version of `docker-compose.sync.yml` and `docker-sync.yml` ok for Windows?

I've been using laradock since months with no problem but now I'm trying to get `docker-sync` to work on Docker For Windows (Version 18.03.1-ce-win65 (17513) on Windows 10 Pro (17134) + WSL (Ubuntu 16.04) but as soon as I set

`COMPOSE_FILE=docker-compose.yml;docker-compose.sync.yml`
I always get the following error after any compose command:
> ERROR: In file '.\docker-compose.sync.yml', service must be a mapping, not a NoneType.

I tried it with a fresh laradock copy, modifying only the .env file as described but the same happened.

My relevant settings:
```
APP_CODE_PATH_HOST=../www
APP_CODE_PATH_CONTAINER=/var/www:nocopy
COMPOSE_FILE=docker-compose.yml;docker-compose.sync.yml
COMPOSE_PATH_SEPARATOR=;
COMPOSE_CONVERT_WINDOWS_PATHS=1
DOCKER_SYNC_STRATEGY=unison
```

If I remove that `services:` line from `docker-compose.sync.yml`, the error disappears, unison can start successfully, but when the app containers are starting, there's some other error:

> ERROR: for workspace Cannot create container for service workspace: invalid volume specification: '/host_mnt/c/Docker/laravel/www:/var/www:nocopy': invalid mount config for type "bind": field VolumeOptions must not be specified

After 2 days spent on this I've just no more idea how could I fix it.

**Comment by godbout** [comment]
Same issue here. The ```:nocopy``` breaks the mounting of the containers.

**Comment by coderars** [comment]
@godbout I was able to get it working on Windows, changing these files as follows:

docker-compose.sync.yml
```yaml
version: '3'

services:
  workspace:
    volumes:
      - applications-docker-sync:/var/www:nocopy
  php-fpm:
    volumes:
      - applications-docker-sync:/var/www:nocopy
  nginx:
    volumes:
      - applications-docker-sync:/var/www:nocopy

volumes:
  applications-docker-sync:
    external: true
```
and docker-sync.yml
```yaml
version: "2"

options:
  verbose: false
  compose-dev-file-path: 'docker-compose.sync.yml' # docker-compose override file
  
syncs:
  applications-docker-sync: # name of the intermediary sync volume
    sync_strategy: '${DOCKER_SYNC_STRATEGY}' # for osx use 'native_osx', for windows use 'unison'
    src: '${APP_CODE_PATH_HOST}' # host source directory
    sync_userid: 1000 # giving permissions to www-data user (as defined in nginx and php-fpm Dockerfiles)
    sync_excludes: ['laradock', 'ignored_folder_example'] # ignored directories
```
...and then in WSL bash:
```bash
./sync.sh up nginx mysql redis maildev
```
Now the unison sync is working as desired and my Laravel app's response time went down from ~700ms to ~50ms. Wow!

But... Next problem is now that on a file change event Laravel's mix with `browserSync` reloads the browser faster than the unison sync completes. LOL :) I see no changes in the browser after automatic reload, only after pressing F5. With browserSync option `reloadDelay: 1000` it works, but that way `docker-sync` is useless. 

My watcher is running by Windows in a Powershell terminal, watching the original files, not the synced ones sitting on that synced volume. I tried running `npm run watch` inside the workspace container but for some reason it was eating up my CPU.

**Comment by godbout** [comment]
@coderars a slight difference with you maybe is that I've redefined all the volumes for each services I use:

```
version: '3'

services:
  apache2:
    volumes:
      - ums-sync:/var/www:nocopy
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
  php-fpm:
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ums-sync:/var/www:nocopy
  workspace:
    volumes:
      - ums-sync:/var/www:nocopy

volumes:
  ums-sync:
    external: true
```

I expect the whole array of volumes to be overridden. But maybe I'm wrong.
