### ISSUE TITLE
Can't Run php artisan migrate on workspace container

### ISSUE THREAD

**Issue by lozadaOmr** [LaraDock/laradock#125]
I tried running `php artisan migrate` in the workspace container but got the following error.

> [PDOException]                                                                           
>   SQLSTATE[HY000] [1130] Host '172.18.0.1' is not allowed to connect to this MySQL server 

Here is my docker-compose.yml

```
mysql:
    build: ./mysql
    volumes_from:
        - data
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: pca
        MYSQL_USER: pca
        MYSQL_PASSWORD: pca
        MYSQL_ROOT_PASSWORD: root
```

Here is my .env file

```
DB_HOST=172.17.0.1
DB_DATABASE=pca
DB_USERNAME=pca
DB_PASSWORD=pca
```
