### ISSUE TITLE
mysql user & password won't change no matter what I do

### ISSUE THREAD

**Issue by Boggimedes** [laradock/laradock#1260]
### Info:
- Docker version (17.09.0-ce, build afdb6d4): 
- Laradock commit (848ff359f927e4b82d1ebb4f00e53e411ea0d1bd): 
- System info: Linux
- System info disto/version: Fedora 26

### Issue:

It does not seem to matter what I put in my env file, the database user and password is not created/changed.  I am doing a simple build apache2 mysql. I've tried deleting the volumes, removing the containers, rebuilding, even creating a user with an sql script in /docker-entrypoint-initdb.d, but that script doesn't appear to run at all.  I've scoured forums and tried every suggestion but nothing seems to work.  No matter what I do the only users are root and default and the root password is 'root'

### Expected behavior:

User and password should be created based on the .env file
Also, scripts in /docker-entrypoint-initdb.d are supposed to be run when the container is built.

### Reproduce:

I don't know.  I followed the laradock setup guide and most settings are at default.  However I doubt it can be reproduced so easily, or everyone would be having the issue.

### Relevant Code:

```
### MySQL Container #########################################

    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend


### MYSQL ##############################################################################################################

MYSQL_VERSION=8.0
MYSQL_DATABASE=homestead
MYSQL_USER=homestead
MYSQL_PASSWORD=secret
MYSQL_ROOT_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ALLOW_EMPTY_PASSWORD=true
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```
