### ISSUE TITLE
Laradock change permissions on host mysql DB

### ISSUE THREAD

**Issue by ddeath** [LaraDock/laradock#127]
Hi there when I run

    docker-compose up -d nginx mysql

and then 

    docker-compose down

The permissions on my host in folder

    /var/lib/mysql

are change so all my local system have a problem.... This is really dangerous and I do not understand why the docker changes my permissions on local machine... :/

**Comment by Kauhat** [comment]
This seems weird. Can you try replacing the `data` container definitions in your `docker-compose.yml` file with the below:

```yaml
### Databases Data Container ################################

    data:
        build: ./data
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/postgres:/var/lib/postgres
            - ./data/mariadb:/var/lib/mariadb
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/neo4j:/var/lib/neo4j/data
            - ./data/mongo:/data/db
```

...that should store the database files in a directory local to your Laradock installation.

I'm not entirely sure what the purpose of binding to `/var/lib` is - perhaps so that you can use existing databases on your system? It does sound a little scary!
