### ISSUE TITLE
Adding Neo4j. Laravel cannot establish connection.

### ISSUE THREAD

**Issue by oberoivarun** [laradock/laradock#1300]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.0-ce, build afdb6d4
- Laradock commit (`$ git rev-parse HEAD`): 4e486280f4ecc7eeb00751575a0541583a136be5
- System info (Mac, PC, Linux): Windows 10 Pro
- System info disto/version: 

### Issue:

I need Neo4j for a project. The existing setup wasnt working for me. So i changed it:
Neo4j DockerFile
```
FROM neo4j:3.1.2

VOLUME /var/lib/neo4j/data
VOLUME /var/lib/neo4j/plugins
VOLUME /var/lib/neo4j/conf

EXPOSE 7474 1337 7687

```

Changed this part of the `docker-compose.yml`
```

### Neo4j Container #########################################

    neo4j:
      build: ./neo4j
      ports:
        - "7474:7474"
        - "1337:1337"
        - "7687:7687"
      environment:
        - NEO4J_HEAP_MEMORY=2048
        - NEO4J_CACHE_MEMORY=1G
        - NEO4J_AUTH=neo4j/neo4j
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        - NEO4J_dbms_connector_http__address=0.0.0.0:7474
        - NEO4J_dbms_connector_bolt__address=0.0.0.0:7687
      volumes:
        - ${DATA_SAVE_PATH}/neo4j:/var/lib/neo4j/data
        - ${DATA_SAVE_PATH}/neo4j/plugins:/var/lib/neo4j/plugins
        - ${DATA_SAVE_PATH}/neo4j/conf:/var/lib/neo4j/conf
      networks:
        - backend
```

### Expected behavior:

Laravel Eloquent cannot connect to Neoe4j: Throws the following error:

```
root@fac2aa3ef6cc:/var/www# php artisan tinker
Psy Shell v0.8.15 (PHP 7.1.11-1+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> App\Client::find(0);
Vinelab\NeoEloquent\QueryException with message 'Can't open connection to http://localhost:7474/db/data/'
```

### Reproduce:

Just setup a blank project with the changes above and do a `docker-compose up nginx neo4j` Setup laravel database default as defined in https://github.com/Vinelab/NeoEloquent

I can access Neo4j via opening `localhost::7474` in the browser. But Laravel cannot. What am i missing?
