### ISSUE TITLE
No way to authorize private channels in laravel-echo-server

### ISSUE THREAD

**Issue by slavarazum** [laradock/laradock#1340]
### Info:
- Docker version (`$ docker --version`): Docker version 17.09.1-ce, build 19e2cf6
- Laradock commit (`$ git rev-parse HEAD`): 9e996cc8ba6fa112cc24fe8d4d2ef9a3a7f3342b
- System info (Mac, PC, Linux): Mac

### Issue:

Laravel echo server private channel authentication impossible with different domain names on nginx.
For example I have several domain names in my *nginx* container and I want to setup my *laravel-echo-server* to specific one for example: `my-site.com`
If I set `"authHost": "http://my-site.com"`, echo server couldn't connect to this host and throws an error
>Error: connect ECONNREFUSED 127.0.0.1:80

because it doesn't know what is it.
But if I set `"authHost": "http://nginx"` it will successfully connect to the nginx server but only to default project with `server_name localhost;`

### Expected behavior:
Ability to set `authHost` to any domain available in web server.
As a result - have an ability to authorize private channels on each of projects under laradock.
_____

### Reproduce:
Try to connect to any private channel on laravel application registered on different domain with simple authentication like:
```php
Broadcast::channel('echo.{id}', function ($user, $id) {
    return true;
});
```

**Comment by ModernArtisan** [comment]
Still no solutions?

**Comment by canhkieu** [comment]
Hi @ModernArtisan, I meet the same issues. Do you resolve?

**Comment by cre8** [comment]
@cabrerabywaters I found a solution for nginx:

nginx config for laravel application:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name api.example.com;
    root /var/www/api/public;
    index index.php;
    
    ssl_certificate /var/certs/cert.pem;
    ssl_certificate_key /var/certs/privkey.pem;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
```

laravel-echo-server config:
```
{
	"authHost": "https://nginx",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "redis"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "https",
	"socketio": {},
	"sslCertPath": "/var/certs/cert.pem",
	"sslKeyPath": "/var/certs/privkey.pem"
}
```

I managed to call api.example.com in my laravel-echo-server by passing the domain in the docker-compose file to one container. But I deleted the file and now I have no idea how to reproduce it.

**Comment by canhkieu** [comment]
It's not work.

**Comment by cre8** [comment]
@canhkieu I can't help you without any logs. What is in the logs of the laravel-echo-server? What exactly does not work? More information is required

**Comment by cre8** [comment]
To address `aaa.com` or `bbb.com` you should insert a redirect in the nginx config like:

```
server {
    ....
    server_name localhost;
    
    location /aaa {
        rewrite ^/(.*)$ https://aaa.com/$1 redirect;
    }

    location /bbb {
        rewrite ^/(.*)$ https://bbb.com/$1 redirect;
    }
}
```

So when you set `authHost` to `https://nginx/aaa` it will route to nginx, that will redirect to the request to `aaa.com` (I haven't tested it yet, but the logic seems to be correct)

Normally you have to set the `host` to `aaa.com` in the http-header when you call `https://nginx`, but this is not implemented in the laravel-echo-server package.

**Comment by aymanterra** [comment]
set
 ` "authHost": "http://my-site.com"`
 as you need , and change your  hosts  file to map your domain to the container IP ,  like this : 
`10.0.75.1		my-site.com`
it will be the IP in the laradock   .env  file 
`DOCKER_HOST_IP=10.0.75.1`
this will solve the problem

**Comment by kongkx** [comment]
I solve this problem by adding an alias to nginx service in `docker-compose.yml`

reference:  [aliases in Compose file reference ](https://docs.docker.com/compose/compose-file/#aliases);

```yml

### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        # before ----
        # - frontend
        # - backend
        # end before ----
        frontend:
        backend:
            aliases:
              - my-site.com
```

`laravel-echo-server.json`
```
{
  " authHost: "http://my-site.com"
  // ...
}
```

extra note: 

1. use `docker-compose up laravel-echo-server`, without `-d` for easier debug;
2. rebuild larvavel-echo-server after updating the `laravel-echo-server.json`, `docker-compose build laravel-echo-server`

extra extra note:

I'm new to docker.
