### ISSUE TITLE
Multiple mySQL databases - unable to connect to 2nd instance

### ISSUE THREAD

**Issue by philbrowne** [laradock/laradock#1415]
### Info:
- Docker version (`$ docker --version`): 17.03.2-ce, build f5ec1e2
- Laradock commit (`$ git rev-parse HEAD`): c4aef8e901a867a57df0b1aadf1c872165e65295
- System info (Mac, PC, Linux): Linux(RedHat 6)
- System info disto/version: 

### Issue:
On single server, I have a laradock_a project and I want to create a laradock_b project. Both use MySQL but I do not want to share the same instance. I have changed the port number on project b to 7706 for MySQL, and also changed apache and phpmyadmin. I can access apache and phpmyadmin via the new port mappings but I cannot access MySQL via phpmyadmin or docker exec -ti mysql_container_name bash. I have tried
mysql -uroot -p and mysql -uroot -p -P7706 and I get
**ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)** 

my .env has POST=7706, and  and I can see ports listening when I netstat
tcp6       0      0 :::3306                 :::*                    LISTEN  
tcp6       0      0 :::7706                 :::*                    LISTEN 

How do I connect to the 2nd MySQL database? And, should I change anything to do with the mounting of the database when I create a 2nd MySQL database?

### Expected behavior:
I should be able to log into MySQL. 
**UPDATE**: I can do this if I do docker-compose down on laradock_a project, BUT when I log in to laradock_b I can see the tables from project_a rather than have a completely clean instance. How do I separate the two?
_____

### Reproduce:

_____

### Relevant Code:

.env
```
MYSQL_PORT=7706
```
docker-compose.yml
```
### MySQL Container #########################################

    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend
      restart: always
```
mysql Dockerfile
```
FROM mysql:8.0

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

#####################################
# Set Timezone
#####################################

ARG TZ=UTC
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN chown -R mysql:root /var/lib/mysql/

ADD my.cnf /etc/mysql/conf.d/my.cnf

CMD ["mysqld"]

EXPOSE 3306
```
my.cnf
```
# The MySQL  Client configuration file.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

[mysql]

[mysqld]
port=7706
sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
character-set-server=utf8
```
