### ISSUE TITLE
Can't execute client:add in laravel-echo-server container.

### ISSUE THREAD

**Issue by ugurkankya** [laradock/laradock#1452]
Hello,

I'm unable to execute client:add in the laravel-echo-server container, client's key is empty as well.

How do i need to execute the command properly ?

Regards

**Comment by cre8** [comment]
@ugurkankya I thinks it's because your config file is in `read-only` mode:

```
laravel-echo-server:
      build:
        context: ./laravel-echo-server
      volumes:
        - ./laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
```
Pls remove the `:ro` in your docker compose file and tell us the result.
