### ISSUE TITLE
try to add pm2 to run nuxtjs app on nginx

### ISSUE THREAD

**Issue by Qanah** [laradock/laradock#1459]
### Info:
- Docker version (`$ docker --version`): 18.03.0-ce, build 0520e24
- Laradock commit (`$ git rev-parse HEAD`): fb686fec15c6b51cd06a96e42542b72ebb277d6c
- System info (Mac, PC, Linux): Mac
- System info disto/version: 

### Issue:
my app is laravel api and nuxt js to fronted 
My folder structure look like this:

```
+ laravel
    + laradock
    + client
```

first i add to docker-compose.yml
```
pm2:
      build:
        context: ./pm2
      ports:
        - "${PM2_PORT}:3000"
      volumes_from:
        - applications
      networks:
        - frontend
        - backend
```

from http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/
```
FROM keymetrics/pm2:latest-alpine

WORKDIR /var/www/client

COPY pm2.json .

CMD [ "pm2-runtime", "start", "pm2.json" ]

EXPOSE 3000
```
on nginx i add this config
https://nuxtjs.org/faq/nginx-proxy
```
server {

    listen 80;
    listen [::]:80;

    server_name client.com www.client.com;

    location / {
        proxy_redirect                      off;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_read_timeout                  1m;
        proxy_connect_timeout               1m;
        proxy_pass                          http://127.0.0.1:3000;
    }

    error_log /var/log/nginx/client_error.log;
    access_log /var/log/nginx/client_access.log;
}
```
i spin 3 days on this issue i dont have any experience on docker please any one can help me
i just get 502 Bad Gateway form  nginx put the api is working will by grate laradock
