### ISSUE TITLE
Caddy up exited

### ISSUE THREAD

**Issue by shouhuori** [laradock/laradock#1576]
### Info:
- Docker version `18.03.1-ce`: 
- Laradock commit `6.0.0`: 
- System info `ubuntu 16.04`: 

### Issue:
```
Starting laradock_caddy_1
Attaching to laradock_caddy_1
caddy_1                | http plugins loaded: git, cors
caddy_1                | Activating privacy features...
caddy_1                |
caddy_1                | Your sites will be served over HTTPS automatically using Let's Encrypt.
caddy_1                | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
caddy_1                |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
caddy_1                | Do you agree to the terms? (y/n): 2018/05/28 19:21:32 user must agree to CA terms (use -agree flag)
laradock_caddy_1 exited with code 1
```

**Comment by Rahulsharma0810** [comment]
Try this

```
### Caddy Server #########################################
    caddy:
      build: ./caddy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${CADDY_CUSTOM_CADDYFILE}:/etc/Caddyfile
        - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
        - ${DATA_PATH_HOST}:/root/.caddy
      stdin_open: true
      tty: true
      ports:
        - "${CADDY_HOST_HTTP_PORT}:80"
        - "${CADDY_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

```
