### ISSUE TITLE
close

### ISSUE THREAD

**Issue by ducxinh-dn-2083199001091997201644783** [laradock/laradock#1578]
close

**Comment by bestlong** [comment]
if your mysql db can delete and .env DATA_PATH_HOST=~/.laradock/data
then `rm ~/.laradock/data/mysql`

**Comment by ducxinh-dn-2083199001091997201644783** [comment]
I already remove all directory and file  in ~/.laradock.
and create new docker-machine. but error still happen. Please help me to fix this issue.

```
rm -rf ~/.laradock/
docker-machine create -d virtualbox common
eval $(docker-machine env common)
git clone https://github.com/laradock/laradock.git common_laradock
cd common_laradock
cp env-example .env
docker-compose build --no-cache mysql
docker-compose up -d mysql
```
- Run `docker-compose ps` and get following result 
|name|command|State|Port|
|-|-|-|-|
|common_laradock_mysql_1|docker-entrypoint.sh mysqld |Exit 1||

- Run `docker-compose up mysql` and get error message
```
[ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
```

- .env
```
APP_CODE_PATH_HOST=../
APP_CODE_PATH_CONTAINER=/var/www:cached
DATA_PATH_HOST=~/.laradock/data
VOLUMES_DRIVER=local
NETWORKS_DRIVER=bridge
COMPOSE_FILE=docker-compose.yml

### MYSQL #################################################

MYSQL_VERSION=5.7
MYSQL_DATABASE=default
MYSQL_USER=default
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```
- docker-compose.yml
```
version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:
    ### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend
```

- mysql/Dockerile
```
ARG MYSQL_VERSION=5.7
FROM mysql:${MYSQL_VERSION}

LABEL maintainer="Mahmoud Zalt <mahmoud@zalt.me>"

#####################################
# Set Timezone
#####################################

ARG TZ=UTC
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN chown -R mysql:root /var/lib/mysql/

COPY my.cnf /etc/mysql/conf.d/my.cnf

CMD ["mysqld"]

EXPOSE 3306
```

- mysql/my.conf
```
# The MySQL  Client configuration file.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

[mysql]

[mysqld]
sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
character-set-server=utf8

```

**Comment by ducxinh-dn-2083199001091997201644783** [comment]
@bestlong 
I change volumn and It's work
```
volumes:
   mysql:
      driver: ${VOLUMES_DRIVER}
services:
   mysql:
       volumes:
           - mysql:/var/lib/mysql
```
