### ISSUE TITLE
 listen tcp 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by wedojava** [LaraDock/laradock#16]
-  When I run `docker-compose up`,there is a error alert blow:
```
Starting data
redis is up-to-date
mysql is up-to-date
Starting php-nginx
ERROR: failed to create endpoint php-nginx on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
```

-  My OS is Ubuntu 15,it had no nginx or apache service.And **PHP+NGINX** config in `docker-compose.yml` is blow:
```
php-nginx:
  image: laradock/phpnginx:latest
  container_name: php-nginx
  ports:
    - "80:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - ../:/var/www
    - ./logs/nginx:/var/log/nginx
  links:
    - mysql
    - redis
  privileged: true
  extra_hosts:
    - "laravel.dev:127.0.0.1"
```
-  My laravel project root dir is `git/Code/hfcms/`,the docker dir is `git/Code/hfcms/docker`.
