### ISSUE TITLE
I cant connect php my admin

### ISSUE THREAD

**Issue by murilolivorato** [laradock/laradock#1694]
Hello , I am using Doker version: '3' .
I am trying to connect to the php my admin , but I cant  . have a look in the error -
![screen shot 2018-07-08 at 8 36 49 pm](https://user-images.githubusercontent.com/19832238/42425137-b96a7ee8-82ee-11e8-97e3-c657e121ef25.png)

this is my .ENV file -

```
### PHP MY ADMIN ##########################################

# Accepted values: mariadb - mysql

PMA_DB_ENGINE=mysql

# Credentials/Port:

PMA_USER=default
PMA_PASSWORD=secret
PMA_ROOT_PASSWORD=secret
PMA_PORT=8080


```

doker-compose.yml

```
### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend
```
please , some one help me .
thanks
