### ISSUE TITLE
What does volumes do? We have DATA_PATH_HOST, who using docker  volumes

### ISSUE THREAD

**Issue by springjk** [laradock/laradock#1757]
In `docker-compose.yml`, all service using `DATA_PATH_HOST` to save data, nobody using docker volumes, so who is using docker volumes? why still here?

**for examle**:
```
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
```

It's bind a host directory, so i think mysql volume is unnecessary.

```
volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
```

I am confused. Can someone tell me why?

**BTW**:
Is that a mistake? `.data` is a old version path, should it be use `${DATA_PATH_HOST}/certbot/certs`？

```
certbot:
      build:
        context: ./certbot
      volumes:
        - ./data/certbot/certs/:/var/certs
```
