### ISSUE TITLE
Postgre connection 'no pg_hba.conf entry for host'

### ISSUE THREAD

**Issue by ThanhToaiPhan** [laradock/laradock#1773]
### Info:
- System info : Linux 16.04
- Laradock : lasted release
- Laravel : 5.6

### Issue:
So I'm trying to set up a simple laravel project with laradock. I have `nginx`, `postgres`, `pgadmin`, `redis`, `pdadmin` and `workspace` (my project) as container and they have been all `Up` normally. But it seems like I cannot connect to postgre when I run `php artisan migrate:status` inside my `workspace`. The error was
```
PDOException with message 'SQLSTATE[08006] [7] FATAL:  no pg_hba.conf entry for host "172.20.0.5", user "default", database "default", SSL off'
```

### Relevant Code:
My postgre setup was
In laravel `.env`
```
DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret
```
In laradock `.env`
```
POSTGRES_DB=default
POSTGRES_USER=default
POSTGRES_PASSWORD=secret
POSTGRES_PORT=5432
POSTGRES_ENTRYPOINT_INITDB=./postgres/docker-entrypoint-initdb.d
```
In `docker-compose.yml`
```
### PostgreSQL ###########################################
    postgres:
      build: ./postgres
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
        - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend
```
