### ISSUE TITLE
still error 500 however docker-compose up is all right.

### ISSUE THREAD

**Issue by wedojava** [LaraDock/laradock#18]
My laravel site dir like this:  `~/git/code/hfcms.dev`.
I cloned your git to the root of my site,the dir like this: `~/git/code/hfcms.dev/docker`

Than,I run `docker-compose up`,and it running up,when I use chrome and visit http://hfcms.dev ,chrome response **Page not working and 500**.

Here is my `~/git/code/hfcms.dev/docker/docker-compose.yml` file:
```
###########################################################
#      MAINTAINER: Mahmoud Zalt <mahmoud@zalt.me>         #
###########################################################

# PHP + NGINX Container #----------------------------------
php-nginx:
  image: laradock/phpnginx:latest
  container_name: php-nginx
  ports:
    - "80:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - ../:/var/www
    - ./logs/nginx:/var/log/nginx
  links:
    - mysql
    - redis
  privileged: true
  extra_hosts:
    - "hfcms.dev:127.0.0.1"

# MySQL Container #----------------------------------------
mysql:
  image: laradock/mysql:latest
  container_name: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - data
  environment:
    MYSQL_DATABASE: hfcms_dev
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  privileged: true

# Redis Container #----------------------------------------
redis:
  image: laradock/redis:latest
  container_name: redis
  ports:
    - "6379:6379"
  volumes_from:
    - data
  volumes:
    - ./logs/redis:/var/log/redis
  restart: always
  privileged: true

# Data Volume Container #----------------------------------
data:
  image: laradock/data:latest
  container_name: data
  volumes:
    - /var/lib/mysql
    - /var/lib/redis

# Beanstalkd Container #-----------------------------------
# beanstalkd:
#   image: laradock/beanstalkd:latest
#   container_name: beanstalkd
#   ports:
#     - "11300:11300"
#   privileged: true

#----------------------------------------------------------
```

And this is my `~/git/code/hfcms.dev/.env` file：

```
APP_ENV=local
APP_DEBUG=true
APP_KEY=qibNQE0AK3dAMQ0FkXcSS1TgajRni12e
APP_URL=http://hfcms.dev

DB_HOST=hfcms.dev
DB_PORT=3306
DB_DATABASE=hfcms_dev
DB_USERNAME=homestead
DB_PASSWORD=secret

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=hfcms.dev
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```
