### ISSUE TITLE
Curl timeout between sites, hosted on same docker

### ISSUE THREAD

**Issue by Hironate** [laradock/laradock#1884]
I have also same issue,

I have multiple websites hosted on my digital ocean server. All on same ip address on same docker. i have created different vhosts in apache2/sites.

One of my domain is analytics.dytest.in and other is services.dytest.in

when application hosted on services.dytest.in tries to curl some api on analytics.dytest.in connection gets time out. tried every possible way like extra_hosts in php-fpm but nothing works.

Not: my websites are running on internet so there is no local environment. domains are pointed to server ip address.

Plz someone help. here is my php-fpm docker compose

```
extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        - "griffon.dytest.in:${DOCKER_HOST_IP}"
        - "analytics.dytest.in:${DOCKER_HOST_IP}"
        - "services.dytest.in:${DOCKER_HOST_IP}"

environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2375
        - FAKETIME=${PHP_FPM_FAKETIME}
      depends_on:
        - workspace
      networks:
        - backend
      links:
        - docker-in-docker
```
