### ISSUE TITLE
Can not add percona docker

### ISSUE THREAD

**Issue by FubuBy** [LaraDock/laradock#206]
Hi. I want replace MySQL on Percona-server
I edited docker-compose.yml:

```
### Percona Server Container #########################################
percona:
        build: ./percona
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            PERCONA_DATABASE: homestead
            PERCONA_USER: homestead
            PERCONA_PASSWORD: secret
            PERCONA_ROOT_PASSWORD: root


### Databases Data Container ################################

    volumes_data:
        build: ./volumes/data
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - /var/lib/percona:/var/lib/percona
            - /var/lib/postgres:/var/lib/postgres
            - /var/lib/mariadb:/var/lib/mariadb
            - /var/lib/memcached:/var/lib/memcached
            - /var/lib/redis:/data
            - /var/lib/neo4j:/var/lib/neo4j/data
            - /var/lib/mongo:/data/db

```
And added file ./percona/Dockerfile:

```
FROM percona:latest

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

CMD ["percona"]

EXPOSE 3306
```

Then I built and started:

```
$ docker-compose build percona
Building percona
Step 1 : FROM percona:latest
 ---> ed3fc6a159be
Step 2 : MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>
 ---> Using cache
 ---> dd075b9694ff
Step 3 : CMD percona
 ---> Using cache
 ---> 258b24346c9d
Step 4 : EXPOSE 3306
 ---> Using cache
 ---> 8a41c63e37e1
Successfully built 8a41c63e37e1
```

```
$ docker-compose up -d  nginx percona
Starting laradock_volumes_source_1
Recreating laradock_volumes_data_1
laradock_workspace_1 is up-to-date
laradock_php-fpm_1 is up-to-date
laradock_nginx_1 is up-to-date
Recreating laradock_percona_1
```

```
$ docker-compose ps
          Name                        Command               State                      Ports                   
--------------------------------------------------------------------------------------------------------------
laradock_mongo_1            /entrypoint.sh mongod          Exit 0     0.0.0.0:27017->27017/tcp                 
laradock_mysql_1            docker-entrypoint.sh mysqld    Exit 0     0.0.0.0:3306->3306/tcp                   
laradock_nginx_1            nginx                          Up         0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp 
laradock_percona_1          docker-entrypoint.sh percona   Exit 127                                            
laradock_php-fpm_1          php-fpm                        Up         9000/tcp                                 
laradock_volumes_data_1     true                           Exit 0                                              
laradock_volumes_source_1   true                           Exit 0                                              
laradock_workspace_1        /sbin/my_init                  Up  
```

But percona contaner didn't start. What I did wrong?
