### ISSUE TITLE
Can't start certbot. - cp: cannot stat [...] cert.pem

### ISSUE THREAD

**Issue by mkubus** [laradock/laradock#2092]
### Info:
- Docker version (`$ docker --version`): 
Docker version 18.06.1-ce, build e68fc7a

- Laradock commit (`$ git rev-parse HEAD`): 
83a24efa709d15037b0d06ca7f4df235e240d642
- System info (Mac, PC, Linux): 
Linux
- System info disto/version:
 Ubuntu 18.04.1 LTS

### Issue:
Certbot exited with code 1

$ docker-compose up certbot
Starting certbot_1 ... 
Starting certbot_1 ... done
Attaching to certbot_1
certbot_1              | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1              | Plugins selected: Authenticator webroot, Installer None
certbot_1              | Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
certbot_1              | Unable to register an account with ACME server
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/"mydomain.pl"/cert1.pem': No such file or directory
certbot_1              | cp: cannot stat '/etc/letsencrypt/archive/"mydomain.pl"/privkey1.pem': No such file or directory
znajdzrower_certbot_1 exited with code 1

### Relevant Code:

```
mk@mkubus-Vostro-5568:~/workspace/laradock$ cat docker-compose.yml |grep -i certbot -A 5
### Certbot #########################################
    certbot:
      build:
        context: ./certbot
      volumes:
        - ./data/certbot/certs/:/var/certs
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      environment:
        - CN="mydomain.pl"
        - EMAIL="my.email@gmail.com"
      networks:
        - frontend

```
