### ISSUE TITLE
gitlab-runner registered but throws error

### ISSUE THREAD

**Issue by sevillaarvin** [laradock/laradock#2129]
### Info:
- Docker version (`$ docker --version`): **Docker version 18.09.6, build 481bc77**
- Laradock commit (`$ git rev-parse HEAD`): **c7289f7db3b96be585a879ceaf0f208102f8233f**
- System info (Mac, PC, Linux) (`$ uname -a`): **Linux *** 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**
- System info distro/version (`$ lsb_release -a`): **elementary OS 5.0 Juno**

### Issue:
gitlab-runner throws an error during job execution
_____

### Expected behavior:
gitlab-runner to run successfully
_____

### Reproduce:
1. Start gitlab and retrieve runner registration token
`docker-compose up -d gitlab`
2. Modify .env file*
```
GITLAB_CI_SERVER_URL=http://gitlab
GITLAB_RUNNER_REGISTRATION_TOKEN=uQ2xyYTUDVVDtRgLxNzz
```
3. Modify docker-compose.yml (add networks: tag in gitlab-runner)*
```
    gitlab-runner:
      image: gitlab/gitlab-runner:latest
      environment:
        - CI_SERVER_URL=${GITLAB_CI_SERVER_URL}
        - REGISTRATION_TOKEN=${GITLAB_RUNNER_REGISTRATION_TOKEN}
        - RUNNER_NAME=${COMPOSE_PROJECT_NAME}-runner
        - REGISTER_NON_INTERACTIVE=${GITLAB_REGISTER_NON_INTERACTIVE}
        - RUNNER_EXECUTOR=shell
      volumes:
        - ${DATA_PATH_HOST}/gitlab/runner:/etc/gitlab-runner
        - /var/run/docker.sock:/var/run/docker.sock:rw
      networks:
        - backend
```
4. Start gitlab-runner
`docker-compose up -d gitlab gitlab-runner`
5. Register gitlab-runner
```
docker-compose exec gitlab-runner bash
gitlab-runner register
```
6. Confirm registration at `Settings > CI / CD > Runners`
7. Push code with the following .gitlab-ci.yml (Test script per https://docs.gitlab.com/ce/ci/introduction/)
```
before_script:
  - apt-get install rubygems ruby-dev -y

run-test:
  script:
    - ruby --version
```
_____

### Relevant Code:
*Initially I couldn't register the gitlab-runner out of the box, hence the step 2 and 3. However after registration, the runner executes the run-test job above, and outputs the following error:
```
Running with gitlab-runner 11.10.1 (1f513601)
  on laradock-runner pVzsSz4s
Using Shell executor...
Running on 8843859c1642...
Initialized empty Git repository in /home/gitlab-runner/builds/pVzsSz4s/0/root/my-project/.git/
Fetching changes...
Created fresh repository.
fatal: unable to access 'http://gitlab-ci-token:[MASKED]@localhost/root/my-project.git/': Failed to connect to localhost port 80: Connection refused
ERROR: Job failed: exit status 1
```
I also don't understand why it's trying to connect to localhost, when .env file is configured as `GITLAB_CI_SERVER_URL=http://gitlab`
Here is the `cat /etc/gitlab-runner/config.toml` for reference:
```
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "laradock-runner"
  url = "http://gitlab"
  token = "HrFQkYHZf41NKECrtLxS"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "laradock-runner"
  url = "http://gitlab"
  token = "DWoYSFT3qdcXxk_escbZ"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "laradock-runner"
  url = "http://gitlab"
  token = "pVzsSz4sn_6vzyVABQa7"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
```
