### ISSUE TITLE
laradock_postgres container exist immediately after starting

### ISSUE THREAD

**Issue by menadio** [laradock/laradock#2189]
### Info:
- Docker version (`$ docker --version`): 18.06.0-ce
- Laradock commit (`$ git rev-parse HEAD`): ca80dd1
- System info (Mac, PC, Linux): PC (Dell Inspiron 7573)
- System info disto/version: Windows 10 Home

### Issue:

This is my first attempt using laradock for containerizing a laravel app using Docker Toolbox on windows. I tried to set up an nginx, postgres and pgadmin environment but only the postgres container fails. So it gets started then exits immediately. The logs show that the error 
```
FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
HINT:  The server must be started by the user that owns the data directory.
```

### Expected behavior:

Like nginx server and pgadmin containers, postgres container should be up so the laravel app can be connected.

### Reproduce:

docker-compose up -d postgres

### Relevant Code:
Full log
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
2019-06-28 14:27:44.010 UTC [47] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
2019-06-28 14:27:44.010 UTC [47] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ...
```

**Comment by raducristyan** [comment]
This issue can be fixed by creating a volume and ataching it to postgres container. I had the same issue on Windows 10.

**Comment by marcelogarbin** [comment]
> This issue can be fixed by creating a volume and ataching it to postgres container. I had the same issue on Windows 10.

How did you do it? could show the settings/code? Thanks

**Comment by dendihandian** [comment]
```
docker-compose up -d postgres pgadmin
```

```
C:\Users\dhn\git\laradock>docker-compose ps
           Name                          Command                State                         Ports                     
------------------------------------------------------------------------------------------------------------------------
laradock_docker-in-docker_1   dockerd-entrypoint.sh            Exit 128   2375/tcp, 2376/tcp                            
laradock_mysql_1              docker-entrypoint.sh mysqld      Exit 255   0.0.0.0:3306->3306/tcp, 33060/tcp             
laradock_nginx_1              /bin/bash /opt/startup.sh        Exit 255   0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp,     
                                                                          0.0.0.0:81->81/tcp                            
laradock_pgadmin_1            /entrypoint.sh                   Up         443/tcp, 0.0.0.0:5050->80/tcp                 
laradock_php-fpm_1            docker-php-entrypoint php-fpm    Exit 255   9000/tcp                                      
laradock_phpmyadmin_1         /docker-entrypoint.sh apac ...   Exit 255   0.0.0.0:8081->80/tcp                          
laradock_postgres_1           docker-entrypoint.sh postgres    Exit 1                                                   
laradock_workspace_1          /sbin/my_init                    Exit 255   0.0.0.0:2222->22/tcp, 0.0.0.0:8001->8000/tcp, 
                                                                          0.0.0.0:8080->8080/tcp
```

```
C:\Users\dhn\git\laradock>docker-compose logs postgres
Attaching to laradock_postgres_1
postgres_1             | The files belonging to this database system will be owned by user "postgres".
postgres_1             | This user must also own the server process.
postgres_1             |
postgres_1             | The database cluster will be initialized with locale "en_US.utf8".
postgres_1             | The default database encoding has accordingly been set to "UTF8".
postgres_1             | The default text search configuration will be set to "english".
postgres_1             |
postgres_1             | Data page checksums are disabled.
postgres_1             |
postgres_1             | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1             | creating subdirectories ... ok
postgres_1             | selecting default max_connections ... 20
postgres_1             | selecting default shared_buffers ... 400kB
postgres_1             | selecting default timezone ... UTC
postgres_1             | selecting dynamic shared memory implementation ... posix
postgres_1             | creating configuration files ... ok
postgres_1             | 2020-05-30 16:16:26.186 UTC [47] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
postgres_1             | 2020-05-30 16:16:26.186 UTC [47] HINT:  The server must be started by the user that owns the data directory.
postgres_1             | child process exited with exit code 1
postgres_1             | initdb: removing contents of data directory "/var/lib/postgresql/data"
postgres_1             | running bootstrap script ...
```

**Comment by dendihandian** [comment]
My solution:

1. modify the `docker-compose.yml` :

```
### PostgreSQL ###########################################
    postgres:
      build:
        context: ./postgres
        args:
          - POSTGRES_VERSION=${POSTGRES_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
        - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - PG_DATA=/var/lib/postgresql/data
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - GITLAB_POSTGRES_INIT=${GITLAB_POSTGRES_INIT}
        - GITLAB_POSTGRES_USER=${GITLAB_POSTGRES_USER}
        - GITLAB_POSTGRES_PASSWORD=${GITLAB_POSTGRES_PASSWORD}
        - GITLAB_POSTGRES_DB=${GITLAB_POSTGRES_DB}
        - JUPYTERHUB_POSTGRES_INIT=${JUPYTERHUB_POSTGRES_INIT}
        - JUPYTERHUB_POSTGRES_USER=${JUPYTERHUB_POSTGRES_USER}
        - JUPYTERHUB_POSTGRES_PASSWORD=${JUPYTERHUB_POSTGRES_PASSWORD}
        - JUPYTERHUB_POSTGRES_DB=${JUPYTERHUB_POSTGRES_DB}
        - SONARQUBE_POSTGRES_INIT=${SONARQUBE_POSTGRES_INIT}
        - SONARQUBE_POSTGRES_DB=${SONARQUBE_POSTGRES_DB}
        - SONARQUBE_POSTGRES_USER=${SONARQUBE_POSTGRES_USER}
        - SONARQUBE_POSTGRES_PASSWORD=${SONARQUBE_POSTGRES_PASSWORD}
        - POSTGRES_CONFLUENCE_INIT=${CONFLUENCE_POSTGRES_INIT}
        - POSTGRES_CONFLUENCE_DB=${CONFLUENCE_POSTGRES_DB}
        - POSTGRES_CONFLUENCE_USER=${CONFLUENCE_POSTGRES_USER}
        - POSTGRES_CONFLUENCE_PASSWORD=${CONFLUENCE_POSTGRES_PASSWORD}
      networks:
        - backend
```

2. Make sure you delete first the `postgres` folder in ./laradock/data (NOTE: I can't help you to restore existing data later, so consider not todo my solution then)

3. rebuild the container using `docker-compose build --no-cache postgres`

4. re-run the container using `docker-compose up -d postgres`
