### ISSUE TITLE
怎样在laradock增加filebeat

### ISSUE THREAD

**Issue by lzwmt** [laradock/laradock#2244]

**Comment by yunlongw** [comment]
**1、在 docker-compose.yml 中增加配置**
```
### Filebate ##############################################
    filebate:
      build: ./filebate
      volumes:
        - '${APP_CODE_PATH_HOST}project/runtime/log:/var/www/log/dev'
        - '${APP_CODE_PATH_HOST}project/runtime/log:/var/www/log/test'
        - '/www/wwwlogs:/var/www/log/nginx'
        - './filebate/config/filebeat.yml:/usr/share/filebeat/filebeat.yml'
      env_file:
        - .env
      networks:
        - frontend
        - backend
```
**2、创建配置文件**
/filebate/config/filebeat.yml

**3、增加 Dockerfile**
```
FROM docker.elastic.co/beats/filebeat:6.5.4

COPY ./config/filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml

USER filebeat
```
