### ISSUE TITLE
phpMyAdmin import db size 

### ISSUE THREAD

**Issue by akhalid4493** [laradock/laradock#2344]
when creating new droplet with Docker 5:19.03.1~3 on 18.04 and change laradock .env mysql version from latest  to 5.7
after use :
docker-compose up -d --build
docker-compose up -d nginx phpmyadmin mysql workspace

I can't import database sql file large than 2 MB.
how can I increases the phpmyadmin importing database limit !!

<img width="984" alt="Screen Shot 2019-10-28 at 3 04 30 PM" src="https://user-images.githubusercontent.com/45354705/67677697-c01bc700-f995-11e9-9cc1-f342d6be8e38.png">

**Comment by slamgundam** [comment]
I also have the same issue.

**Comment by llioor** [comment]
+1

**Comment by bharatgupta99** [comment]
same issue.

**Comment by llioor** [comment]
> same issue.

I logged into the container of phpmyadmin and mysql and I changed to properties of max post size and upload file manually to a bigger size.

**Comment by Sunvers** [comment]
+1

**Comment by jfm-dnd** [comment]
Hi, I had the same issue and have found a workaround with adding `./php-ini/php.ini:/usr/local/etc/php/php.ini` to pma volumes section.
I use [docker4php](https://github.com/wodby/docker4php), so pma section in docker-compose.yml file looks like:
```
pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: root
      PMA_PASSWORD: $DB_ROOT_PASSWORD
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"
    volumes:
      - /sessions
      - ./php-ini/php.ini:/usr/local/etc/php/php.ini
```
Then create a dir /php-ini with a php.ini file at the same level of the docker-compose.yml. Adding `post_max_size=400M` to it and restart override phpmyadmin, and it works.
I recently made a reminder from the result of my research, with a structure in example [https://github.com/jfm-dnd/docker4php-multiproject](https://github.com/jfm-dnd/docker4php-multiproject). (sorry I did it in french).
