### ISSUE TITLE
Elasticsearch 5.6.16 shutdown after few seconds of usage 

### ISSUE THREAD

**Issue by mtuchi** [laradock/laradock#2345]
### Info:
- Docker version (`$ Docker version 19.03.4, build 9013bf5`): 
- Laradock commit (`04c6aaf (origin/master, origin/HEAD) Merge pull request #2215 from stefnats/gearman`): 
- System info (Mac): 
- System info disto/version:  (Mac Os Catalina version 10.15)

### Issue:

Elasticsearch shutdown after few minutes of using it from my app
_____

### Expected behavior:

_____
Elasticsearch should work just fine without shutting down

### Reproduce:

_____
Elasticsearch Dockerfile 
```
ARG ELASTICSEARCH_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}

EXPOSE 9200 9300
```
In docker-compose.yml
```
### ElasticSearch ########################################
    elasticsearch:
      build: 
        context: ./elasticsearch
        args:
          - ELASTICSEARCH_VERSION=${ELASTICSEARCH_VERSION}
      volumes:
        - elasticsearch:/usr/share/elasticsearch/data
      environment:
        - cluster.name=${ELASTICSEARCH_CLUSTER}
        - node.name=${ELASTICSEARCH_NODE}
        # - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        # - cluster.initial_master_nodes=${ELASTICSEARCH_NODE}
        - http.cors.enabled=true
        - http.cors.allow-origin=*
        - xpack.security.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        # - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend
```

In `.env`
```
### ELASTICSEARCH #########################################
ELASTICSEARCH_VERSION=5.6.16
ELASTICSEARCH_HOST_HTTP_PORT=9200
# ELASTICSEARCH_HOST_TRANSPORT_PORT=9300
ELASTICSEARCH_CLUSTER=dockstack-cluster
ELASTICSEARCH_NODE=dockstack-node
```

### Error logs:
[view error logs](https://gist.github.com/mtuchi/281f18b23b9c7ad49c770c951595f417)
