### ISSUE TITLE
Is node installed?

### ISSUE THREAD

**Issue by nojaf** [LaraDock/laradock#243]
I've enabled node in my docker-compose.yml

```yaml
    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_NODE=true
                - INSTALL_DRUSH=false
                - COMPOSER_GLOBAL_INSTALL=false
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        tty: true
```

But when I enter the workspace container
```docker exec -it laradock_workspace_1 bash```

```
root@090e4d583908:/var/www/laravel# node -v
bash: node: command not found
```

Using the latest LaraDock code.
Maybe it's installed but not on my path
```
root@090e4d583908:/var/www/laravel# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/laravel/vendor/bin
```
Where would the node installation be located?
