### ISSUE TITLE
Cannot access PhpMyAdmin within ssl-site

### ISSUE THREAD

**Issue by rammi22** [laradock/laradock#2439]
### Info:
- Docker version: Docker version 19.03.5, build 633a0ea
- Laradock commit: 67e9a517f33f014252de9d2f9e8255cd2b2a1a2b
- System info: PC
- System info disto/version: Win10

### Issue:
I cannot access the phpMyAdmin if my application is **runnig in ssl**. 
Error: **PR_END_OF_FILE_ERROR**

I'm following Setup for Multiple Projects
My folder structure:
- laradock-tut
-- laradock (contains the laradock)
-- project-http (contains laravel 6)
-- project-https (contains laravel 6)

calling the pages:
**http** http://docker-training.laradock-project-http.local
**https** http://docker-training.laradock-project-https.local
Both url's works fine

If i call the http-url (http://docker-training.laradock-project-http.local:8080) i have access to phpMyAdmin. But **using the https-url** (http://docker-training.laradock-project-https.local:4843), it **response with the error**. 

I haven't found anything about the configuration in the docu...
_____

### Expected behavior:
Accessing phpMyAdmin from both url's
_____

### Reproduce:
calling the https-url http://docker-training.laradock-project-https.local:8080
_____

### Relevant Code:
laradock/ngingx/sites/project-http.config
```
server {

    listen 80;
    listen [::]:80;

    server_name docker-training.laradock-project-http.local;
    root /var/www/project_http/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

    error_log /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
}
```

laradock/ngingx/sites/project-https.config
```
server {

    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;
    ssl_certificate /etc/nginx/ssl/default.crt;
    ssl_certificate_key /etc/nginx/ssl/default.key;

    server_name docker-training.laradock-project-https.local;
    root /var/www/project_http/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

    error_log /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
}
```
phpmyadmin/Dockerfile
```
FROM phpmyadmin/phpmyadmin

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>"

# Add volume for sessions to allow session persistence
VOLUME /sessions

RUN echo '' >> /usr/local/etc/php/conf.d/php-phpmyadmin.ini \
 && echo '[PHP]' >> /usr/local/etc/php/conf.d/php-phpmyadmin.ini \
 && echo 'post_max_size = 2G' >> /usr/local/etc/php/conf.d/php-phpmyadmin.ini \
 && echo 'upload_max_filesize = 2G' >> /usr/local/etc/php/conf.d/php-phpmyadmin.ini

# We expose phpMyAdmin on port 80
EXPOSE 80 443
```
docker-composer.yml
```
...
### phpMyAdmin ###########################################
    phpmyadmin:
      build: ./phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - MYSQL_USER=${PMA_USER}
        - MYSQL_PASSWORD=${PMA_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      ports:
#        - "${PMA_PORT_HTTP}:80"
#        - "${PMA_PORT_HTTPS}:443"
        - "8080:80"
        - "4843:443"
      depends_on:
        - "${PMA_DB_ENGINE}"
      networks:
        - frontend
        - backend
...
````
