### ISSUE TITLE
Cannot log into MSSQL Server. SA password cannot be reset

### ISSUE THREAD

**Issue by bdteo** [laradock/laradock#2462]
### Info:
- Docker version (`$ docker --version`): Docker version 18.09.7, build 2d0083d
- Laradock commit (`$ git rev-parse HEAD`): 0d086024a8b7cff30f45860fe28c9ae896281bc8
- System info (Mac, PC, Linux): Linux
- System info disto/version: Ubuntu 18.04

### Issue:

The `/opt/mssql/bin/mssql-conf set-sa-password` script does not work at all.
Not only that it does not work but after running it actually empties the /var/opt/mssql/mssql.conf file.

MSSQL ignores all environment variables passed to it - SA_PASSWORD or MSSQL_SA_PASSWORD. Checked for both of them. Checked whether environment variables are passed to the target process - they are.

Deleted all MSSQL's data from ~/.laradock/data, rebuilt the MSSQL container without cache (tried it many variations of the latter), MSSQL does not pick the password coming from the .env file (the SA_PASSWORD / MSSQL_SA_PASSWORD environment variables) at all.

MSSQL Server just completely ignores all environment variables passed to it at startup, no matter that Microsoft loudly claim in their documentation that they should have effect.

These circumstances  combined make it impossible to change MSSQL's password, impossible to log in and impossible to use the MSSQL container from Laradock at all.

### Expected behavior:

At least one of the SA_PASSWORD / MSSQL_SA_PASSWORD environment variables should take effect (blaming it on Microsoft). 

The `/opt/mssql/bin/mssql-conf set-sa-password` should work or there should be some adequate way to set the password at least when building a container (maybe some custom initialization script that gets the password from the .env file and crams it into the MSSQL thing).

### Reproduce:

Just checkout Laradock at 0d086024a8b7cff30f45860fe28c9ae896281bc8 and build a MSSQL container. Set some password for MSSQL in the .env file (like `SomeWeirdP1sswordThatFullfillsAllTheWeirdMicrosoftRequirements`). Run
`sqlcmd -S 127.0.0.1 -USA -P'SomeWeirdP1sswordThatFullfillsAllTheWeirdMicrosoftRequirements' ` (from the container or the host system if you have `sqlcmd` there).

You will not be able to log in.

Try running `/opt/mssql/bin/mssql-conf set-sa-password`. It will search for sudo but won't work even after installing sudo. It will also empty your `/var/opt/mssql/mssql.conf` file.

**Comment by dgbrown** [comment]
I came across your post when I was facing the same issue. Fortunately, I've figured it out. There's a bug somewhere in the combination of Docker for Windows running linux containers, the mssql for linux docker image, and bind mounting of `var/opt/mssql/` that prevents the container from being set up properly.

I changed a million things, read a million documents, and in the end there's three modifications I made to get a successful config.

1) Run the mssql container as privileged. This is accomplished by adding `privileged: true` to the mssql service definition in your docker-compose.yml
2) Ditch the mssql dockerfile (I deep dived and noticed it doesn't seem to be adding anything to the equation) and just specify the image in the compose file. I also decided to use a newer image `mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04`
3) Bind mount the data, log, and backup directories individually instead of the parent.

The mssql service definition in my docker-compose.yml now looks like the following, and I'm able to successfully connect through sql browers on my host machine:
```
mssql:
      image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
      environment:
        - SA_PASSWORD=${MSSQL_SA_PASSWORD}
        - ACCEPT_EULA=Y
      privileged: true
      volumes:
       - ${DATA_PATH_HOST}/mssql/data:/var/opt/mssql/data
       - ${DATA_PATH_HOST}/mssql/logs:/var/opt/mssql/logs
       - ${DATA_PATH_HOST}/mssql/backup:/var/opt/mssql/backup
      ports:
        - "${MSSQL_PORT}:1433"
      networks:
        - backend
```

Now I have a different issue, with laravel in the php-fpm container not being able to access the db. Maybe you'll figure that one out haha. The error: `{"success":false,"data":null,"error":{"message":"SQLSTATE[HY000] Unable to connect: Adaptive Server is unavailable or does not exist (severity 9)"}}`
