### ISSUE TITLE
Gitlab-runner  having network problems when register

### ISSUE THREAD

**Issue by amung966** [laradock/laradock#2491]
Thanks for help first and sorry about my poor english

### System info:
**I created Centos7 on vm ware , my host system is win10**
```
git rev-parse HEAD : ad2b455be577669aa599f3511704565e6a806629
docker version : Docker version 19.03.5, build 633a0ea
docker-compose version : docker-compose version 1.25.0, build 0a186604
system info : Centos7 Linux localhost.localdomain 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Description:
```
[root@localhost laradock]# docker-compose exec gitlab-runner bash

root@0ac58204e1db:/# gitlab-runner register
Runtime platform      arch=amd64 os=linux pid=28 revision=003fe500 version=12.7.1
Running in system-mode.

ERROR: Registering runner... failed    runner=iSZiPL_m status=couldn't execute POST against http://192.168.229.128:8989/   api/v4/runners: Post http://192.168.229.128:8989/api/v4/runners: dial tcp 192.168.229.128:8989: connect: no route to host
PANIC: Failed to register this runner. Perhaps you are having network problems
```

### Expected Behavior:
```
root@0ac58204e1db:/# gitlab-runner register
Runtime platform      arch=amd64 os=linux pid=28 revision=003fe500 version=12.7.1
...
Runner registered successfully. Feel free to start it, but if it's running already the config should be automatically reloaded!
```

### Issue
I already built gitlab on 8989 port(default), and got runner token form the page (admin area > overview > runners > Set up a shared Runner manually). 
following laradock documents to set up gitlab-runner , and got the error like this
I can't found solution about this error...
 
### Steps to reproduce the issue:

1.Download laradock and init it (cp .env ... etc)
2.Following laradock document (3.Use Gitlab Runner)  to set up gitlab and gitlab-runner
3.Start up gitlab
4.Got token from my gitlab page and set gitlab-runner token
5.Into gitlab-runner container and do register then got error

### Stacktrace & Additional info:
- docker ps
```
[root@localhost laradock]# docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                 PORTS                                                               NAMES
0ac58204e1db        gitlab/gitlab-runner:latest   "/usr/bin/dumb-init …"   2 hours ago         Up 2 hours                                                                                 laradock_gitlab-runner_1
362ece123e84        laradock_gitlab               "/assets/wrapper"        2 hours ago         Up 2 hours (healthy)   0.0.0.0:2289->22/tcp, 0.0.0.0:8989->80/tcp, 0.0.0.0:9898->443/tcp   laradock_gitlab_1
c863d6caffbe        laradock_redis                "docker-entrypoint.s…"   5 days ago          Up 19 hours            0.0.0.0:6379->6379/tcp                                              laradock_redis_1
f8a458de32d6        laradock_postgres             "docker-entrypoint.s…"   5 days ago          Up 19 hours            0.0.0.0:5432->5432/tcp                                              laradock_postgres_1
```

- .env  gitlab & gitlab-runner
```
### GITLAB ###############################################
GITLAB_POSTGRES_INIT=true
GITLAB_HOST_HTTP_PORT=8989
GITLAB_HOST_HTTPS_PORT=9898
GITLAB_HOST_SSH_PORT=2289
GITLAB_DOMAIN_NAME=http://192.168.229.128
GITLAB_ROOT_PASSWORD=laradock
GITLAB_HOST_LOG_PATH=./logs/gitlab
GITLAB_POSTGRES_HOST=postgres
GITLAB_POSTGRES_USER=laradock_gitlab
GITLAB_POSTGRES_PASSWORD=laradock_gitlab
GITLAB_POSTGRES_DB=laradock_gitlab

### GITLAB-RUNNER ###############################################
GITLAB_CI_SERVER_URL=http://192.168.229.128:8989
GITLAB_RUNNER_REGISTRATION_TOKEN=iSZiPL_mezvVLatoEy-H
GITLAB_REGISTER_NON_INTERACTIVE=true
```
- docker-compose.yml
```
### Gitlab ################################################
    gitlab:
      build:
        context: ./gitlab
      hostname: 192.168.229.128 # this centos7 ip
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url '${GITLAB_DOMAIN_NAME}'
          redis['enable'] = false
          nginx['listen_https'] = false
          nginx['listen_port'] = 80
          nginx['custom_gitlab_server_config'] = "set_real_ip_from 172.0.0.0/8;\nreal_ip_header X-Real-IP;\nreal_ip_recursive on;"
          postgresql['enable'] = false
          gitlab_rails['trusted_proxies'] = ['caddy','nginx','apache2']
          gitlab_rails['redis_host'] = 'redis'
          gitlab_rails['redis_database'] = 8
          gitlab_rails['db_host'] = '${GITLAB_POSTGRES_HOST}'
          gitlab_rails['db_username'] = '${GITLAB_POSTGRES_USER}'
          gitlab_rails['db_password'] = '${GITLAB_POSTGRES_PASSWORD}'
          gitlab_rails['db_database'] = '${GITLAB_POSTGRES_DB}'
          gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
          gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_HOST_SSH_PORT}
      volumes:
        - ${DATA_PATH_HOST}/gitlab/config:/etc/gitlab
        - ${DATA_PATH_HOST}/gitlab/data:/var/opt/gitlab
        - ${GITLAB_HOST_LOG_PATH}:/var/log/gitlab
      ports:
        - "${GITLAB_HOST_HTTP_PORT}:80"
        - "${GITLAB_HOST_HTTPS_PORT}:443"
        - "${GITLAB_HOST_SSH_PORT}:22"
      networks:
        - backend
      depends_on:
        - redis
        - postgres
    gitlab-runner:
      image: gitlab/gitlab-runner:latest
      environment:
        - CI_SERVER_URL=${GITLAB_CI_SERVER_URL}
        - REGISTRATION_TOKEN=${GITLAB_RUNNER_REGISTRATION_TOKEN}
        - RUNNER_NAME=${COMPOSE_PROJECT_NAME}-runner
        - REGISTER_NON_INTERACTIVE=${GITLAB_REGISTER_NON_INTERACTIVE}
        #copy from document
        - RUNNER_EXECUTOR=docker
        - DOCKER_IMAGE=latest
        - DOCKER_NETWORK_MODE=laradock_backend
      volumes:
        - ${DATA_PATH_HOST}/gitlab/runner:/etc/gitlab-runner
        - /var/run/docker.sock:/var/run/docker.sock:rw
      #copy from document
      networks:
        - backend 
```

- iptables 
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
INPUT_direct  all  --  0.0.0.0/0            0.0.0.0/0
INPUT_ZONES_SOURCE  all  --  0.0.0.0/0            0.0.0.0/0
INPUT_ZONES  all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
REJECT     all  --  0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited
...
Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

If need more information , please let's me know , thank you !
