### ISSUE TITLE
Support running LaraDock for multiple projects in parallel

### ISSUE THREAD

**Issue by iannazzi** [LaraDock/laradock#25]
This repository is so good it replaced all my homestead instances....

The problem I am facing is that laradock only runs once with `docker-compose up` on machine `default`. If I have several sites I want to work on, docker-compose-up will shut down the other containers.

What is the best solution - do I want a `docker-machine` for each `docker-compose`? I thought changing ports would work but it does not.

**Comment by Mahmoudz** [comment]
@iannazzi Great request. 

Right now when you run `docker-compose up` in different project it restart the containers and switch to the new project.

One quick way to do it for now is to rename the services/containers and change the ports: in the example below I appended everything with `-b` and added `+1` to every port number:

```yaml
# PHP + NGINX Container #----------------------------------
php-nginx-b:
  image: laradock/php56nginx:0.1.0
  container_name: php-nginx-b
  ports:
    - "81:80"
  volumes:
    - ./settings/nginx:/etc/nginx/sites-available
    - ../:/var/www
    - ./logs/nginx:/var/log/nginx
  links:
    - mysql-b
    - redis-b
  privileged: true

# MySQL Container #----------------------------------------
mysql-b:
  image: laradock/mysql:0.1.0
  container_name: mysql-b
  ports:
    - "3307:3306"
  volumes_from:
    - data-b
  environment:
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  privileged: true

# Redis Container #----------------------------------------
redis-b:
  image: laradock/redis:0.1.0
  container_name: redis-b
  ports:
    - "6380:6379"
  volumes_from:
    - data-b
  volumes:
    - ./logs/redis:/var/log/redis
  restart: always
  privileged: true

# Data Volume Container #----------------------------------
data-b:
  image: laradock/data:0.1.0
  container_name: data-b
  volumes:
    - /var/lib/mysql
    - /var/lib/redis
```

I will upgrade the yaml file syntax to version 2 soon. And will work on the Multi-LaraDock feature to make it much simpler.

**Comment by iannazzi** [comment]
Great, that is just perfect. 
I am assuming we don't want to use multiple virtual box machines, and we do want to use one machine with multiple containers.

**Comment by tristanbailey** [comment]
I think you wouldn't need to suffix the names if you are using docker-compose v2 as you can use networks. It now has multi networks, so if you have an app and compose file in a folder "larasite" and another "greatapp" you would get the app in the compose in network name larasite_default and the other greatapp_default.
Also you can set this in the conf:
Note: Your app’s network is given a name based on the “project name”, which is based on the name of the directory it lives in. You can override the project name with either the --project-name flag or the COMPOSE_PROJECT_NAME environment variable.
https://docs.docker.com/engine/userguide/networking/get-started-overlay/

**Comment by Mahmoudz** [comment]
@tristanbailey thanks for the info. I'm working on this right now. Will update the docs soon.

**Comment by denissceluiko** [comment]
While six years have passed after the opening of this ticket, I hope this helps someone.

## Problem
You have multiple projects, each of them has Laradock installed as a submodule and you want those projects to run in paralell. You launch one project telt's say - `project1.test` and all is fine, you launch another `project2.test` and it refuses to launch as ports are already bound to the host. 

## What you want to achieve
Adding a new `projectN.test` to your dev machine should be as close to `docker compose up -d nginx mysql` as possible.  This solution however only partially addresses this issue and you should decide if this works for your workflow.
> After writing this i realised that initial setup might be a _a tiny bit_ on the long side.

## What you need
1. A reverse proxy container. I'm using [jwilder/nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy).
2. Each new project having a _separate_ Laradock container group. 

## What to do
### Setting up the reverse proxy 

Run `docker network create nginx-proxy`
 
Create a new folder for nginx-proxy in a place of your choosing, I usually host all my projects in `/var/www/[projectX]` so I put it next to them in `/var/www/nginx-proxy`. In that folder create a `docker-compose.yml` with the contents:

```
version: "3.5"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external: true
    driver: bridge
    name: nginx-proxy
```
And go for `docker compose up -d` in that folder.

This reverse proxy will bind to hosts ports 80 and 443 and will be used to accept all incoming reqests to your hodt and then forward them to the appropriate Laradock instance. If this concept is unclear, I suggest some reading of [jwilder/nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy) docs. 

Source & inspiration from [here](https://blog.ssdnodes.com/blog/host-multiple-websites-docker-nginx/).

### Creating/adding the first project
Go to the folder of your existing/new project.
Let's assume you have a new project in `/var/www/projectN`
in that folder go for a quick `git submodule add https://github.com/Laradock/laradock.git laradock-projectN` as [Laradock docs](https://laradock.io/getting-started/#A1) say. Notice the folder name `laradock-projectN` rather than just `laradock`. While both can be used there may be some conflicts when there are multiple projects if going without the `-projectN`. See [this](https://github.com/laradock/laradock/blob/11d387e89420f0d37554e3a66ad6c311b937db6b/.env.example#L35) if you don't want to add `-projectN` suffix so you can define the prefix in the `.env` file rather than the folder name.

Then goes `cp .env.example .env` as per the docs. the, open the new `.env` file.
It should go somewhat like this: 
```
### Paths #################################################

# Point to the path of your applications code on your host
APP_CODE_PATH_HOST=../

# Point to where the `APP_CODE_PATH_HOST` should be in the container
APP_CODE_PATH_CONTAINER=/var/www

# You may add flags to the path `:cached`, `:delegated`. When using Docker Sync add `:nocopy`
APP_CODE_CONTAINER_FLAG=:cached

# Choose storage path on your machine. For all storage systems
DATA_PATH_HOST=~/.laradock/data
```

As Laradock is installed as a submodule in this case `APP_CODE_PATH_HOST` stays the same. In my case so do both `APP_CODE_PATH_CONTAINER` and `APP_CODE_CONTAINER_FLAG`. 
However I change `DATA_PATH_HOST=~/.laradock/data` to `DATA_PATH_HOST=~/.laradock/projectN-data` as I do not want database failiure, this is important. 

After the above environment variables this should be added
```
# Nginx proxy config
VIRTUAL_HOST=projectN.test
NGINX_PROXY_NETWORK=nginx-proxy
```
`VIRTUAL_HOST` is the environment variable our reverse proxy is looking for in every container in the `nginx-proxy` network. This also doubles as the hostname for the project. Don't forget to add this hostname to your `hosts` file or it won't work.

The last thing you need to do in this file is change 
`COMPOSE_FILE=docker-compose.yml` 
to 
`COMPOSE_FILE=docker-compose.yml;docker-compose.reverse-proxy.yml`.
Please notice the semicilon (`;`) between the filenames. If you're using Windows as your host it should stay, otherwise change it to a colon (`:`) here and in `COMPOSE_PATH_SEPARATOR`.

If you wish, you can also change `COMPOSE_PROJECT_NAME` value to `projectN`. This will remove the necessity to change container names as suggested [above](https://github.com/laradock/laradock/issues/25#issuecomment-209552874).
Now we're done with `.env` for now but we'll return.

In the same directory create a file `docker-compose.reverse-proxy.yml` (this is the one referenced in `COMPOSE_FILE` above)
and paste in it the following:
```
services:
  nginx:
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    driver: ${NETWORKS_DRIVER}
```
This will effectively append this configuration to the default nginx configuration in `docker-compose.yml` and expose both ports 80 (HTTP) and 443 (HTTPS) to the networks `nginx-proxy` that is defined here and `frontend` and `backend` that are defined in the default config. Also it will set the `VIRTUAL_HOST` environment variable that our reverse proxy is looking for.

At this point it will almost work, if you do a docker compose up -d nginx mysql in you project's directory only nginx launch should fail as port 80 is already allocated (bound) to the reverse proxy. 

#### Now for the voodoo part.

Every guide I found on the Internet on the topic of running multiple laradocks in parallel (this issue included) adresses `Bind for 0.0.0.0:80 failed: port is already allocated` issue by saying _just change the port numbers_. Tried that and discovered that *it is not easily scalable* as for every project you'd need to change a lot of ports. 
At this point i was sure that i really don't need Laradock's ports to be *bound* to host's, *expose*d is just fine.
After some struggling with `services.nginx.ports must be a list` and `services.nginx.ports.0 must be a number` (I tried to reset the ports list in docker-compose.reverse-proxy.yml which didn't work) I also tried commenting out ports lists in the Laradock's docker-compose.yml which worked but I wanted as little or preferably no modifications to docker-compose.yml. 
After that,

the time was 5AM, the sleepless madness consumed me and I just tried changing .env's NGINX_HOST_HTTP_PORT=80 to NGINX_HOST_HTTP_PORT=0 and also couple other ports that _were already allocated_ and it worked. I guess Docker internally just ignores people trying bind something to port 0. 

### Return to the `.env`
and change whatever these ports there are set to:

```
NGINX_HOST_HTTP_PORT=0
NGINX_HOST_HTTPS_PORT=0
MYSQL_PORT=0
WORKSPACE_SSH_PORT=0
WORKSPACE_BROWSERSYNC_HOST_PORT=0
WORKSPACE_BROWSERSYNC_UI_HOST_PORT=0
WORKSPACE_VUE_CLI_SERVE_HOST_PORT=0
WORKSPACE_VUE_CLI_UI_HOST_PORT=0
WORKSPACE_ANGULAR_CLI_SERVE_HOST_PORT=0
```

Now do a `docker compose up -d nginx mysql` and it should launch without any issues. But only nginx, mysql, workspace and php-fpm will launch clean. If you want additional services that have ports that *bind* to host, e.g., phpmyadmin, the first instance will launch no problems but the second one will throw back the port problem. I will address this further below.

### Creating/adding the second project

1. Add Laradock submodule to the project
2. Copy `.env` from the first project
3. In the new `.env`
    1. Change the project specific paths if necessary 
    2. Change the `VIRTUAL_HOST` to the new projects hostname.
4. Copy `docker-compose.reverse-proxy.yml` from the first project
5. Do a `docker compose up -d nginx mysql`

### How do I run and connect to to my phpMyAdmin? 
> or other services that are usually  *bound*  to host.

No other way that I know of than to bind them to a free port that is dedicatad to that specific project. If there are three projects, there'd be 3 ports necessary to be allocated to be bound. E.g. `PMA_PORT=8081` for project1, `PMA_PORT=8082` for project2, `PMA_PORT=8083` for project3 and so on. 
While you might be able to configure nginx-proxy to forward phpmyadmin (or other HTTP protocol based services) to the correct container similarly as project's Laradock's nginx by adding necessary directives to `docker-compose.reverse-proxy.yml` I'm not sure yet how to do it or whether this could be done to all services so you could just connect to e.g. MySQL server as project1.test:3306 and nginx-proxy would do all the magic of figuring you which container to proxy the request to. Would be nice though. Please let me know if you know how to do it 😄 

### Possible issues
#### HTTP 502 Bad gateway
Solution: check if this particular Laradock instance's nginx is in the nginx proxy network `docker network inspect nginx-proxy` might help.
#### HTTP 503 Service Temporarily Unavailable
Solution: either VIRTUAL_HOST is not set properly or Laradock is not launched for this project.
