### ISSUE TITLE
Error: Class 'MongoClient' not found

### ISSUE THREAD

**Issue by FubuBy** [LaraDock/laradock#254]
I get the error: "Error: Class 'MongoClient' not found" when try work with mongo.

My workspace settings:

```

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=true
                - INSTALL_NODE=false
                - INSTALL_DRUSH=false
                - COMPOSER_GLOBAL_INSTALL=false
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        tty: true

```
My php-fpm settings:
```
php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=true
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"
```

PhpInfo:

```
root@7e128f67e843:/var/www/laravel# php -i|grep mongo
mongodb
mongodb support => enabled
mongodb version => 1.1.8
mongodb stability => stable
libmongoc version => 1.3.5
mongodb.debug => no value => no value
```

What I did wrong?
