### ISSUE TITLE
How to get Wordpress working like phpmyadmin setup.

### ISSUE THREAD

**Issue by geeksupport1** [laradock/laradock#2542]
Hi guys,
Thanks for creating this.

 Can someone point me in the right direction to install wordpress properly.

 I have seen laradock-with-wordpress, but it uses a manual process to install wordpress.

 Is there a way to install wordpress using a dockerfile in a subdirectory like phpmyadmin.

 Can anyone provide a setup?

Thanks in advance.

**Comment by vladyslavstartsev** [comment]
Hi! laradock is not wordpress oriented, but if you want. You can add official wp image to the `docker-compse.yaml`

```yaml
services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

```
