### ISSUE TITLE
macos try to use docker-sync , got a problem at the final step

### ISSUE THREAD

**Issue by sado0823** [laradock/laradock#2543]
i got this error ! how can i fix this ,please help!

ERROR: for laradock_workspace_1  Cannot create container for service workspace: invalid volume specification: '/Users/xxx/Documents/wwwroot:/var/www:nocopy': invalid mount config for type "bind": field VolumeOptions must not be specified

ERROR: for workspace  Cannot create container for service workspace: invalid volume specification: '/Users/xxx/Documents/wwwroot:/var/www:nocopy': invalid mount config for type "bind": field VolumeOptions must not be specified
ERROR: Encountered errors while bringing up the project.

what should i do to this docker-compose.sync.yml file 
version: '3'

services:

volumes:
  applications-sync:
    external:
      name: "applications-docker-sync"

**Comment by beadm** [comment]
+1

**Comment by sado0823** [comment]
> +1

i finally solve this problem ,
use `applications-sync` to replace your mount directory ,
all this you can find in docker-sync document

**Comment by beadm** [comment]
> > +1
> 
> i finally solve this problem ,
> use `applications-sync` to replace your mount directory ,
> all this you can find in docker-sync document

Thanks! Can you tell what to modify exactly in which file?

**Comment by sado0823** [comment]
> > > +1
> > 
> > 
> > i finally solve this problem ,
> > use `applications-sync` to replace your mount directory ,
> > all this you can find in docker-sync document
> 
> Thanks! Can you tell what to modify exactly in which file?

docker-compose.sync.yml

**Comment by beadm** [comment]
@sado0823 can you copy here your docker-compose.sync.yml file?

**Comment by beadm** [comment]
Does anyone has a solution for this?

**Comment by sado0823** [comment]
use applications-sync to replace your mount directory

beadm <notifications@github.com> 于2020年3月31日周二 上午3:19写道：

**Comment by beadm** [comment]
You mean like this?

```
version: '3'

services:
  workspace:
    volumes:
      - applications-docker-sync:/var/www:nocopy
  php-fpm:
    volumes:
      - applications-docker-sync:/var/www:nocopy
  nginx:
    volumes:
      - applications-docker-sync:/var/www:nocopy

volumes:
  applications-sync:
    external:
      name: "applications-docker-sync"
```
