### ISSUE TITLE
Reducing size of data-only volumes

### ISSUE THREAD

**Issue by computerfr33k** [LaraDock/laradock#260]
I found an interesting write-up with using data-only volumes with docker-compose that I think would be wise to use for this project.
Here is the link: https://dockermeetupsinbordeaux.github.io/docker-compose/data-container/2015/03/01/minimalistic-docker-data-container.html

the image he created is only a size of ~125 bytes and provides only what is necessary to get docker-compose to get it to run. This would make much more sense than the current solution which is pulling in the entire debian docker image for no reason since the container is only used for its mountpoints into the other containers.

And so we could do something like this for the data-containers to make them run instantly
```yml
### Laravel Application Code Container ######################

    volumes_source:
        image: tianon/true
#        build: ./volumes/application
        volumes:
            - ../:/var/www/laravel
            # Demonstration of how to mount multiple sites
            # - ../../site_a/:/var/www/site_a
            # - ../../site_b/:/var/www/site_b

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
#        build: ./volumes/data
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/postgres:/var/lib/postgres
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/neo4j:/var/lib/neo4j/data
            - ./data/mongo:/data/db
            - ./data/sessions:/sessions
```
