### ISSUE TITLE
docker-sync  is also slow 

### ISSUE THREAD

**Issue by liminworks** [laradock/laradock#2616]
### Description:
docker-sync is success but also slow 

### Expected Behavior:
quickly

### Context information:

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
Docker version 19.03.8, build afacb8b
```

**Output of `docker-compose version`**

```
docker-compose version 1.25.5, build 8a1c60f6
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
docker for mac 
```

### Steps to reproduce the issue:

  devup nginx mysql redis
Initializing Docker Sync
May take a long time (15min+) on the first run
          ok  Starting native_osx for sync applications-docker-sync
doing initial sync with unison
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
^@^@Reconciling changes
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 15:15:03.02 on 01 Jun 2020
[BGN] Copying .DS_Store from /host_sync to /app_sync
[END] Copying .DS_Store
[BGN] Copying .cache from /host_sync to /app_sync
[END] Copying .cache
[BGN] Copying .svn from /host_sync to /app_sync
[END] Copying .svn
[BGN] Copying advanced from /host_sync to /app_sync
[END] Copying advanced
[BGN] Copying index.php from /host_sync to /app_sync
[END] Copying index.php
[BGN] Copying laradock.bk from /host_sync to /app_sync
[END] Copying laradock.bk
[BGN] Copying laravel from /host_sync to /app_sync
^@[END] Copying laravel
[BGN] Copying weStudyOS from /host_sync to /app_sync
^@[END] Copying weStudyOS
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 15:16:45.96 on 01 Jun 2020
Saving synchronizer state
Synchronization complete at 15:16:46  (8 items transferred, 0 skipped, 0 failed)
real	4m 8.90s
user	0m 6.41s
sys	0m 21.23s
chown ing file to uid 1000
b7005752a5ef2ec7f4df18f8abd2851ea4b959acc59b8adcc7d143ad53e6e4ca
     success  Sync container started
     success  Starting Docker-Sync in the background

### Stacktrace & Additional info:

```
docker-compose.sync.yml 


version: '3'

services:
  workspace:
    volumes:
    - applications-docker-sync:/var/www:nocopy
  php-fpm:
    volumes:
    - applications-docker-sync:/var/www:nocopy
  nginx:
    volumes:
    - applications-docker-sync:/var/www:nocopy
volumes:
  applications-docker-sync:
    external: true

```

```
docker-sync.yml


version: "2"

options:
  verbose: false
syncs:
  applications-docker-sync: # name of the intermediary sync volume
    compose-dev-file-path: 'docker-compose.sync.yml' # docker-compose override file

    src: '${APP_CODE_PATH_HOST}' # host source directory
    sync_userid: 1000 # giving permissions to www-data user (as defined in nginx and php-fpm Dockerfiles)
    sync_strategy: '${DOCKER_SYNC_STRATEGY}' # for osx use 'native_osx', for windows use 'unison'

    sync_excludes: ['laradock', 'ignored_folder_example'] # ignored directories

```

```
###########################################################
###################### General Setup ######################
###########################################################

### Paths #################################################

# Point to the path of your applications code on your host
APP_CODE_PATH_HOST=../

# Point to where the `APP_CODE_PATH_HOST` should be in the container
APP_CODE_PATH_CONTAINER=/var/www

# You may add flags to the path `:cached`, `:delegated`. When using Docker Sync add `:nocopy`
APP_CODE_CONTAINER_FLAG=:nocopy

# Choose storage path on your machine. For all storage systems
DATA_PATH_HOST=~/.laradock/data

### Drivers ################################################

# All volumes driver
VOLUMES_DRIVER=local

# All Networks driver
NETWORKS_DRIVER=bridge

### Docker compose files ##################################

# Select which docker-compose files to include. If using docker-sync append `:docker-compose.sync.yml` at the end
COMPOSE_FILE=docker-compose.yml:docker-compose.sync.yml

# Change the separator from : to ; on Windows
COMPOSE_PATH_SEPARATOR=:

# Define the prefix of container names. This is useful if you have multiple projects that use laradock to have separate containers per project.
COMPOSE_PROJECT_NAME=laradock

### PHP Version ###########################################

# Select a PHP version of the Workspace and PHP-FPM containers (Does not apply to HHVM).
# Accepted values: 7.4 - 7.3 - 7.2 - 7.1 - 7.0 - 5.6
PHP_VERSION=7.2

### Phalcon Version ###########################################

# Select a Phalcon version of the Workspace and PHP-FPM containers (Does not apply to HHVM). Accepted values: 3.4.0+
PHALCON_VERSION=3.4.5

### PHP Interpreter #######################################

# Select the PHP Interpreter. Accepted values: hhvm - php-fpm
PHP_INTERPRETER=php-fpm

### Docker Host IP ########################################

# Enter your Docker Host IP (will be appended to /etc/hosts). Default is `10.0.75.1`
DOCKER_HOST_IP=10.0.75.1

### Remote Interpreter ####################################

# Choose a Remote Interpreter entry matching name. Default is `laradock`
PHP_IDE_CONFIG=serverName=laradock

### Windows Path ##########################################

# A fix for Windows users, to ensure the application path works
COMPOSE_CONVERT_WINDOWS_PATHS=0

### Environment ###########################################

# If you need to change the sources (i.e. to China), set CHANGE_SOURCE to true
CHANGE_SOURCE=true
# Set CHANGE_SOURCE and UBUNTU_SOURCE option if you want to change the Ubuntu system sources.list file.
UBUNTU_SOURCE=aliyun

### Docker Sync ###########################################

# If you are using Docker Sync. For `osx` use 'native_osx', for `windows` use 'unison', for `linux` docker-sync is not required
DOCKER_SYNC_STRATEGY=native_osx

### Install Oh My ZSH! ####################################

# If you want to use "Oh My ZSH!" with Laravel autocomplete plugin, set SHELL_OH_MY_ZSH to true.

SHELL_OH_MY_ZSH=true

###########################################################
################ Containers Customization #################
###########################################################


```

**Comment by linmory** [comment]
docker-compose.sync.yml volumes should no ":nocopy"

```
docker-compose.sync.yml 


version: '3'

services:
  workspace:
    volumes:
    - applications-docker-sync:/var/www
  php-fpm:
    volumes:
    - applications-docker-sync:/var/www
  nginx:
    volumes:
    - applications-docker-sync:/var/www
volumes:
  applications-docker-sync:
    external: true
```
