### ISSUE TITLE
Laravel echo server cannot run on https

### ISSUE THREAD

**Issue by adiramardiani** [laradock/laradock#2769]
### Description:
For all external link, all https recomended to use https version. I want to create laravel-echo-server (6001) to use https

I use this configuration

```
{
	"authHost": "localhost",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": "6379",
			"host": "redis"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "https",
	"socketio": {},
	"sslCertPath": "/etc/nginx/ssl/default.crt",
	"sslKeyPath": "/etc/nginx/ssl/default.key"
}
```

```
### Laravel Echo Server #######################################
    laravel-echo-server:
      build:
        context: ./laravel-echo-server
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
      volumes:
        - ./laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${LARAVEL_ECHO_SERVER_PORT}:6001"
      links:
        - redis
      networks:
        - frontend
        - backend
```

But my laravel-echo-server still use http protocol, I don't know what I miss, I'm new on laradock / docker

I have suggest to have sepparate configuration port like caddy

```
### CADDY #################################################

CADDY_HOST_HTTP_PORT=80
CADDY_HOST_HTTPS_PORT=443
CADDY_HOST_LOG_PATH=./logs/caddy
CADDY_CONFIG_PATH=./caddy/caddy

### LARAVEL ECHO SERVER ###################################

#LARAVEL_ECHO_SERVER_PORT=6001
LARAVEL_ECHO_SERVER_HTTP_PORT=6001
LARAVEL_ECHO_SERVER_HTTPS_PORT=1234
```
