### ISSUE TITLE
Unable to access postgres-postgis with .env file values

### ISSUE THREAD

**Issue by alexc-tti** [laradock/laradock#2922]
### Description:
Running `docker-compose up -d postgres-postgis` does not create a database with the variables set in the .env file (DB: default, user: default, password: secret). Attempting to access the DB using any role (root, postgres, etc) fails saying the role does not exist.

Manually specifying the role and changing the data path does work, e.g.

```
### PostgreSQL PostGis ###################################
    postgres-postgis:
      build: ./postgres-postgis
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql-11/data # Note change of path here
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=default # Manually specified
        - POSTGRES_USER=postgres # Manually specified
        - POSTGRES_PASSWORD=postgres # Manually specified
      networks:
        - backend
```

Connecting to 127.0.0.1 using postgres/postgres shows the databases correctly and allows psql to work through bash.

### Expected Behavior:
Creation of role "default" with password "secret" for access to database "default", as specified in .env.

### Context information:

**Output of `git rev-parse HEAD`**

```
05a45ed0c86f30cce339f1b693a07d6cd169aa7f
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:59 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:40 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
20.04.2 LTS (Focal Fossa)

```

### Steps to reproduce the issue:

1. `docker-compose up -d postgres-postgis` with .env vars set to defaults
2. Attempt to connect to 127.0.0.1 with any PG client --> FAILS
3. Set vars manual and rebuild
4. Attempt to connect to 127.0.0.1 with any PG client --> Succeeds
