### ISSUE TITLE
postgresql container immediately exits

### ISSUE THREAD

**Issue by david-perez** [LaraDock/laradock#299]
Running `docker-compose up -d postgres` does not create the `postgres` container. Instead the container's status shows it exited.

`docker logs`  on the exited `postgres` container yields

```
FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
HINT:  The server must be started by the user that owns the data directory.
```

Could be related to https://github.com/LaraDock/laradock/issues/237.

Running docker for windows `1.12.0-stable`.

**Comment by david-perez** [comment]
Modifying the `volumes_data` container so that the local db data is not mounted solves the issue i.e. in `docker-compose.yml`

```
volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql
            - /var/lib/postgresql/data
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/neo4j:/var/lib/neo4j/data
            - ./data/mongo:/data/db
            - ./data/aerospike:/opt/aerospike/data
            - ./data/sessions:/sessions
            - ./data/elasticsearch/data:/usr/share/elasticsearch/data
```

Now `postgresql` will start successfully.
