### ISSUE TITLE
SSL certificate problem in Laradock (or Workspace?)

### ISSUE THREAD

**Issue by sarukomine** [laradock/laradock#3029]
I am develop Laravel with Mac mini (M1).

I already set up a single Docker environment for all projects (site A, site B, site C...), and generated SSL certs for each project.

So, I can use HTTPS to access these sites via browser. However, if I use PHP's CURL to call **site B API** in **site A**, it will failed, the following is the error message from CURL:
```
SSL certificate problem: unable to get local issuer certificate
```

Although I can set `CURLOPT_SSL_VERIFYHOST` and `CURLOPT_SSL_VERIFYPEER` to `false` but I really 100% don't like this way...

and I had tried to add below codes into `/nginx/Dockerfile` or `/workspace/Dockerfile` files, both are not working for me.

```Dockerfile
RUN mkdir /usr/share/ca-certificates/sample

COPY ssl/site-a.crt /usr/share/ca-certificates/sample/site-a.crt

COPY ssl/site-b.crt /usr/share/ca-certificates/sample/site-b.crt

RUN echo "sample/site-a.crt" >> /etc/ca-certificates.conf && \
    echo "sample/site-b.crt" >> /etc/ca-certificates.conf

RUN chmod 644 /usr/share/ca-certificates/sample/site-a.crt && \
    chmod 644 /usr/share/ca-certificates/sample/site-b.crt && \
    update-ca-certificates
```

so how can I fix it? I don't know that which files that need to be shared. If you want more information, please feel free to let me know :)

.env
```env
...
WEBSERVER_SUBNET=192.168.0.0/16
WEBSERVER_IP_RANGE=192.168.10.0/24
WEBSERVER_GATEWAY=192.168.10.1
WEBSERVER_IP=192.168.10.10
...
```

docker-compose.yml
```yaml
...
networks:
  webserver:
    driver: ${NETWORKS_DRIVER}
    ipam:
      config:
        - subnet: ${WEBSERVER_SUBNET}
          gateway: ${WEBSERVER_GATEWAY}
          ip_range: ${WEBSERVER_IP_RANGE}
...
services:
  php-fpm:
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      - "site-a.test:${WEBSERVER_IP}"
      - "site-b.test:${WEBSERVER_IP}"
    networks:
      - webserver
...
  nginx:
    extra_hosts:
      - "site-a..test:${WEBSERVER_IP}"
      - "site-b.test:${WEBSERVER_IP}"
    networks:
      webserver:
        ipv4_address: ${WEBSERVER_IP}
...
  mysql:
    platform: linux/x86_64
...
```
