### ISSUE TITLE
env_file field in Logstash making impossible to use untouched Laradock project structure

### ISSUE THREAD

**Issue by DJviolin** [laradock/laradock#3146]
### Description:

I try to achieve the following project structure, where I keep Laradock in an untouched git submodule:

```sh
/my-project-folder
    /laradock
    /src
    /wordpress
    .env
    docker-compose.override.yml
```

My `docker-compose.override.yml` looks like this:

```yaml
version: '3.5'

services:

### NGINX Server #########################################
    nginx:
      volumes:
        - '${NGINX_GLOBAL_PATH}:/etc/nginx/global'

### Logstash ##############################################
    logstash:
      env_file: ../.env
```

Lines in `.env`:

```ini
APP_CODE_PATH_HOST=../wordpress
APP_CODE_PATH_CONTAINER=/var/www/wordpress
DATA_PATH_HOST=../.laradock/data
PHP_VERSION=8.1
NGINX_HOST_LOG_PATH=../.laradock/logs/nginx/
NGINX_SITES_PATH=../src/nginx/sites/
NGINX_SSL_PATH=../.laradock/ssl
NGINX_GLOBAL_PATH=../src/nginx/global/
ADM_DEFAULT_SERVER=laradock-mariadb-1
```

I run Docker Compose with this command from `/my-project-folder`:

```powershell
PS docker-compose --env-file .env -f laradock/docker-compose.yml -f docker-compose.override.yml up -d nginx mariadb adminer
```

I'm getting the following error, if I not deleting `env_file:` field from Laradock's `docker-compose.yml`:

```powershell
open C:\my-project-folder\laradock\.env: The specified file cannot be found.
```

### Expected Behavior:

Is there any particular reason why `env_file:` presented in `docker-compose.yml` explicitly? If it wasn't there, it would be much easier to create more delicate deployments to use Laradock as an untouched submodule.

I think the reason why `env_file:` in `docker-compose.override.yml` doesn't replace the field in `laradock/docker-compose.yml`, because simply extending the array with the new value:

```yaml
env_file:
    - .env
    - ../.env
```

### Context information:

**Output of `git rev-parse HEAD`**

```
01ab8c7d1e12f7ed7d6c80651f396ce5661d2583
```

**Output of `docker version`**

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:44:07 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose version`**

```
Docker Compose version v2.2.3
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
PS systeminfo
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
```

<!---### Steps to reproduce the issue:
<!--- How can we reproduce the issue?

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
``` -->

**Comment by DJviolin** [comment]
Stalebot is the most useful invention in human programmer's history.

**Comment by DJviolin** [comment]
Okay stale bot, I will let you close this issue.

**Comment by DJviolin** [comment]
Okay stale bot, I will let you close this issue.

**Comment by zhushaolong** [comment]
You should look at the relationship between the. env file and the Docker Compose instead of associating it with the logstash. --- From Baidu Translation.

**Comment by DJviolin** [comment]
Referencing the entire `.env` file instead of the needed environment variables still a bad practice.

**Comment by zhushaolong** [comment]
Let me show you:
The directory structure is as follows:
```shell
.
├── docker-compose.yml
└── logstash
    ├── Dockerfile
    ├── config
    │   └── logstash.yml
    └── pipeline

4 directories, 3 files
```
The files in the logstash folder are from the laradock logstash folder.

.env file content:
The contents of the .env file are from the laradock .env file.
```env
### ELK Stack ##################################################
ELK_VERSION=7.9.1
```

docker-compose.yml file content:
The contents of the docker-compose.yml file are from the laradock docker-compose.yml file
```yml
logstash:
    build:
        context: ./logstash
        args:
            - ELK_VERSION=${ELK_VERSION}
    volumes:
        - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
        - './logstash/pipeline:/usr/share/logstash/pipeline'
    ports:
        - '5001:5001'
    environment:
        LS_JAVA_OPTS: '-Xmx1g -Xms1g'
    env_file:
        - .env
    networks:
        - frontend
        - backend
    depends_on:
        - elasticsearch
```

You are welcome to try.
