### ISSUE TITLE
DATA_PATH_HOST root (~) directory was created inside laradock folder

### ISSUE THREAD

**Issue by trd-warren** [laradock/laradock#3208]
### Description:
Windows 11 Pro
Docker Desktop 4.7.1 (77678) 
WSL

Hello. Everything works fine for a long time with my local docker. But when I started my containers earlier, I noticed that `MariaDB` data files were created in the wrong place. My directory structure is this:

```
- laradock
- laravel
```

.env
```env
APP_CODE_PATH_HOST=../laravel
DATA_PATH_HOST=~/.laradock/data/projectName
```

docker-compose.yml
```yml
### MariaDB ##############################################
    mariadb:
      image: myrepo/mariadb:10.4.10-bionic-laradock9.5
      volumes:
        - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MARIADB_PORT}:3306"
      environment:
        - TZ=${WORKSPACE_TIMEZONE}
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      networks:
        - backend
```

I started my containers, instead of using the already existing files in the root of WSL ```~/.laradock/data/projectName/mariadb```
it generates new data files inside laradock

```
- laradock/~/.laradock/data/projectName/mariab
```

### Expected Behavior:

Should read data file in the specified ```DATA_PATH_HOST```

### Context information:

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
{paste here}
```

**Output of `docker-compose version`**

```
{paste here}
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
{paste here}
```

### Steps to reproduce the issue:

1.
2.
3.

### Stacktrace & Additional info:

```
{paste here}
```
