### ISSUE TITLE
My MySQL data gets lost 

### ISSUE THREAD

**Issue by jorgemartiinez** [laradock/laradock#3220]
### Description:
Sometimes, without apparent reason, my mysql data disappears and I lose everything, all the databases, configurations, etc. What annoys me is that I've installed Laradock on two or three servers already and this have happened in all of them. 

### Expected Behavior:
I expect to keep the data on my volumes and don't lose my databases, the default path is `~/.laradock/data/mysql`. I don't see a pattern of why it gets deleted.

This is the content of my docker-compose.yml. The configuration of the volumes looks correct to me:

```
### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend
```

### Context information:

**Output of `git rev-parse HEAD`**
```
{33828f81bf07de83ebfec1fa3abe7ef530e2b125}
```

**Output of `docker version`**

```
{Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:18:18 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:16:22 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
}
```

**Output of `docker-compose version`**

```
{docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.4
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
}
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
{Ubuntu 22.04}
```

### Steps to reproduce the issue:

1. This is the command that I use to start my containers every time `docker-compose up -d nginx mysql php-worker`, when it doesn't exists it just creates the necessary stuff to make them work automatically.

### Stacktrace & Additional info:

```
{}
```
