### ISSUE TITLE
Execute the command "docker inspect laradock_mysql_1" to view the container information IPAddress is empty, use Navicat to connect to mysql: 127.0.0.1 is rejected

### ISSUE THREAD

**Issue by xiaoyanger2016** [laradock/laradock#3433]
Navicat: 2003 - Can't connect to MySQL server on '127.0.0.1' (61 "Connection refused")

### Description:
docker-compose up -d nginx mysql redis workspace
```
Creating network "laradock_frontend" with driver "bridge"
Creating network "laradock_backend" with driver "bridge"
Creating network "laradock_default" with the default driver
Creating laradock_docker-in-docker_1 ... done
Creating laradock_redis_1            ... done
Creating laradock_mysql_1            ... done
Creating laradock_workspace_1        ... done
Creating laradock_php-fpm_1          ... done
Creating laradock_nginx_1            ... done
```

docker-compose ps
![image](https://github.com/laradock/laradock/assets/18712144/1e82c99e-d38e-44ae-b6df-f292ac84835e)

execute the command: `docker inspect laradock_mysql_1`, IPAddress is found to be a null character
```
"Gateway": "",
"IPAddress": "",
```
![image](https://github.com/laradock/laradock/assets/18712144/66bfdef8-dfee-46dd-a396-fedc9c40d83b)

But executing the command "docker inspect laradock_nginx_1" found that IPAddress is not empty。
![image](https://github.com/laradock/laradock/assets/18712144/99214a1a-c194-4a09-9294-8b94b324430f)

### Context information:

**Output of `git rev-parse HEAD`**

```
d6a523e8bc4e6f77200d182d33a64740944338c6
(HEAD detached at v13.0)
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose version`**

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
macOS Monterey 12.1
```

### Steps to reproduce the issue:

1. Execute the command: `docker inspect laradock_mysql_1` found that ipAddress is empty
2. Using Navicat to connect to mysql localhost is refused
Navicat: 2003 - Can't connect to MySQL server on '127.0.0.1' (61 "Connection refused")
```
MYSQL_VERSION=latest
MYSQL_DATABASE=default
MYSQL_USER=root
MYSQL_PASSWORD=secret
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_ENTRYPOINT_INITDB=./mysql/docker-entrypoint-initdb.d
```
3.Execute the following command to view container information IPAddress is also empty：
```
docker inspect laradock_mysql_1            
docker inspect laradock_postgres_1 
```

### Stacktrace & Additional info:

docker-compose.yml
```
version: '3.3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  percona:
    driver: ${VOLUMES_DRIVER}
  mssql:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  memcached:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  neo4j:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  minio:
    driver: ${VOLUMES_DRIVER}
  rethinkdb:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}
  adminer:
    driver: ${VOLUMES_DRIVER}
  aerospike:
    driver: ${VOLUMES_DRIVER}
  caddy:
    driver: ${VOLUMES_DRIVER}
  meilisearch:
    driver: ${VOLUMES_DRIVER}
  elasticsearch:
    driver: ${VOLUMES_DRIVER}
  mosquitto:
    driver: ${VOLUMES_DRIVER}
  confluence:
    driver: ${VOLUMES_DRIVER}
  sonarqube:
    driver: ${VOLUMES_DRIVER}
  cassandra:
    driver: ${VOLUMES_DRIVER}
  graylog:
    driver: ${VOLUMES_DRIVER}
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}
  react:
    driver: ${VOLUMES_DRIVER}

### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - frontend
        - backend
```
