### ISSUE TITLE
How can I connect to mysql from outside? Like Workbrench

### ISSUE THREAD

**Issue by pablorsk** [laradock/laradock#344]
Hi! My project is working fine with this commands:

```
docker-compose up -d  nginx mysql
docker-compose exec workspace bash
```

Also, http://localhost/ work too. But, How can I connect to mysql from outside? Like Workbrench...

I try with `localhost` and `mysql`

If you need more information:

.env:

```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

``` bash
$ docker-compose -v && docker -v
docker-compose version 1.8.0-rc2, build c72c966
Docker version 1.12.1, build 23cf638
```

```
$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                      NAMES
892bb636969f        laradock_nginx       "nginx"                  23 minutes ago      Up 23 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   laradock_nginx_1
b1a66108ce2f        laradock_php-fpm     "php-fpm"                23 minutes ago      Up 23 minutes       9000/tcp                                   laradock_php-fpm_1
04e14870a1be        laradock_workspace   "/sbin/my_init"          23 minutes ago      Up 23 minutes       0.0.0.0:22->22/tcp                         laradock_workspace_1
2b79a787595f        laradock_mysql       "docker-entrypoint.sh"   23 minutes ago      Up 23 minutes       3306/tcp                                   laradock_mysql_1
```

**Comment by philtrep** [comment]
@pablorsk 

You can forward the MySQL port to your host by adding the lines
```
ports:
    - "3306:3306"
```
To the mysql section of the LaraDock `docker-compose.yml` or in your (environment specific Compose)[https://docs.docker.com/compose/extends/] file.

It would end up looking something like:

```
### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
```
