### ISSUE TITLE
Add ngx_pagespeed in Nginx

### ISSUE THREAD

**Issue by philtrep** [laradock/laradock#346]
This idea comes from #316 (the original issue was split in two since the proposed features are not related).

**Comment by philtrep** [comment]
If has an idea for this, we're more than open to it

**Comment by g0ld3lux** [comment]
Hi mate , Im the One who initially suggested this ...
Ive Already Posted for Certbot
 
Certbot is Ok as a Separate Container...

But I doubt with this another image i found...
since it consumes the port of our main container nginx...

https://github.com/wunderkraut/alpine-nginx-pagespeed

Either we Drop our Main Nginx container and replace it with this one....

or We Build Our Separate Container for with Nginx Module...

But i got No Idea if that would work...

Please Check my Idea if it is possible...  and Test it...

**Comment by g0ld3lux** [comment]
From that repo i think we can create a more flexible container
that has an option to enable pagespeed...

which will be done on docker-compose.yml
this will replace the default nginx we have that we can pass an ARG to enable pagespeed installation

we need to tweak a bit https://github.com/wunderkraut/alpine-nginx-pagespeed
to accept argument from our docker-compose which will conditionally install it...

while we add another container for cerbot
using this image https://github.com/jwanglof/docker-alpine-nginx-letsencrypt
Ive check this one didnt install the nginx only certbot...

docker-comppose.yml
```
nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
                - PAGE_SPEED=true
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
certbot:
        build:
            context: ./certbot
        volumes:
            - ./certbot/letsencrypt/:/etc/nginx/letsencrypt

```
We still need to Polish it and test... but i hope you get the idea
