### ISSUE TITLE
Debugger not installed

### ISSUE THREAD

**Issue by hopewise** [laradock/laradock#381]
In PHPStorm setting of remote interpreter, I can see that Debugger not installed like here:
![screen shot 2016-10-20 at 5 05 09 pm](https://cloud.githubusercontent.com/assets/1061157/19563139/9ca8f554-96e7-11e6-8a9e-68c883efaa66.png)

However, in docker-compose.yml, I have `INSTALL_XDEBUG=true` as:

```
workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=false
                - INSTALL_NODE=false
                - INSTALL_DRUSH=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=true
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "docker host:172.17.0.1
        ports:
           - "223:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "docker host:172.17.0.1
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `larval`"
            - PHP_IDE_CONFIG="serverName=laravel"
```

So, why its not installed?
