### ISSUE TITLE
Updating mysql configuration to reflect in mysql docker container

### ISSUE THREAD

**Issue by whsiao** [laradock/laradock#383]
Hello
I'm new to laradock and I'm trying to update the mysql config in the docker-composer.yml with this code block in the laradock directory:

```
### MySQL Container #########################################
mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: JenkinsJobTest
            MYSQL_USER: test2
            MYSQL_PASSWORD: password1
            MYSQL_ROOT_PASSWORD: password1
```

I was able to change the ports from "3306:3306" to "3306:3307", but I was not able to update the mysql root password from the default password.  I've tried a few approaches to this problem.
1.  Searching and changing the default password "root" through my project and the laradock directory (in the laravel directory) and have not been able to update the root password for the mysql container.
2.  Rebuilding the docker containers with this command

```
docker-compose up --build -d nginx mysql
```

and that doesn't seem to update the root password.

Is there some configuration that I need to set in order to change the password for the mysql container?  I rather not go into the container to do a manual update of the mysql database root password.

**Comment by appleboy** [comment]
Try the following steps:

remove all container:

```
docker-compose down
```

rebuild container with `--no-cache` flag:

```
docker-compose build --no-cache nginx mysql
```

**Comment by whsiao** [comment]
Thank you for replying.  I've tried the steps, and unfortunately that didn't change the default password to the one I specified in my code example.

I tried changing the format of the configuration to the code:
```
### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_DATABASE:JenkinsJobTest"
            - "MYSQL_USER:test2"
            - "MYSQL_PASSWORD:password1"
            - "MYSQL_ROOT_PASSWORD:password1"
```

The configuration I tried above didn't change the password default to password1.

**Comment by appleboy** [comment]
Try the following format of environment:

```
    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: JenkinsJobTest
            MYSQL_USER: test2
            MYSQL_PASSWORD: password1
            MYSQL_ROOT_PASSWORD: password1
```

**Comment by whsiao** [comment]
I tried that configuration, and it is still not working.  Also I tried changing the mysql port with this:

```
mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3307"
        environment:
            MYSQL_DATABASE: JenkinsJobTest
            MYSQL_USER: test2
            MYSQL_PASSWORD: password1
            MYSQL_ROOT_PASSWORD: password1
```
But when I ran `docker-compose build --no-cache mysql`, it did not change the port from 3306 to 3307 instead it kept to 3306.

Output from build:
```
docker-compose build --no-cache mysql
Building mysql
Step 1 : FROM mysql:5.6
 ---> a07c28d2a09a
Step 2 : MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>
 ---> Running in 7c1a8a142e15
 ---> 5fb454163c17
Removing intermediate container 7c1a8a142e15
Step 3 : ADD my.cnf /etc/mysql/conf.d/my.cnf
 ---> 0d5b7e0c3c63
Removing intermediate container 6acecd0880dc
Step 4 : CMD mysqld
 ---> Running in 236121f6f5a1
 ---> 136f2b6fc644
Removing intermediate container 236121f6f5a1
Step 5 : EXPOSE 3306
 ---> Running in 598d2ea9ac08
 ---> 7dc9a34533db
Removing intermediate container 598d2ea9ac08
Successfully built 7dc9a34533db
```

  Is there some step I need to do to setup database and laravel environment before running 'docker-compose up mysql'.  Some permissions I need to set to allow the changes in docker-composer.yml in the laradock directory to change the docker images configuration?  Do I need to setup a docker-composer.yml outside the laravedock directory?

**Comment by appleboy** [comment]
Please update as following.

```diff
        ports:
-           - "3306:3307"
+           - "3307:3306"
```

**Comment by whsiao** [comment]
Thanks.  Got that part working.  Still trying to figure out why the environment information is not being used in the spin up of the mysql docker container.

**Comment by philtrep** [comment]
@whsiao please take a look at #404, I think you have a similar issue

**Comment by whsiao** [comment]
@philtrep Yeah it is the same as #404.  I actually got the mysql container to work with the new root password.  My friend was working with me on the problem and found that that volume_data was was not taking in the changes from the docker-compose.yml.  He had me scrapped the laradock directory and pull in a fresh clone of laradock.  He found that the `volumes_from` with `-volumes_from:` was somehow interfering with the build of the container.

part that was breaking for me:
```
 mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
```

fresh laradock clone that works:
```
 mysql:
        build: ./mysql
        volumes:
            - mysql:/var/lib/mysql
```

Note this is for one mysql version spin up that I am working on.  Not sure how if it will help with the @markdev in #404, since the issue is about spinning up two instances of mysql.
