### ISSUE TITLE
Trying to connect to mysql via a port other than 3306

### ISSUE THREAD

**Issue by markdev** [laradock/laradock#404]
I am trying to run two different instances of the mysql image (one for production, one for integration testing).  I need to assign these instances to different ports (ideally "prod" talks to port 1306 and "test" talks to 2306), but I cannot get `workspace` to talk to anything other than port 3306.

Here's my attempt to get a connection to 1306:

docker-compose.yml:
```
### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        environment:
            MYSQL_DATABASE: laradock
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "1306:3306"
```

.env:
```
DB_CONNECTION=prod
DB_HOST=mysql
DB_PORT=1306
...
```

database/config.php:
```
   'connections' => [
        'prod' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1306'),
```

When I run `docker-compose up -d workspace nginx mysql` everything seems to work.  However, when I `docker-compose exec workspace bash` and then `php artisan migrate`, I get this error:

```
  [PDOException]                             
  SQLSTATE[HY000] [2002] Connection refused 
```

Once I switch `DB_PORT` in `.env` to 3306, the migration runs.  It seems like `workspace` was talking to 3306 the whole time.

How can I configure laradock so that I can specify which port I connect to mysql with?

**Comment by philtrep** [comment]
@markdev The MySQL image exposes port `3306` to the other services by default.

The `port` option in the Docker Compose config is for forwarding the port to the host.

You need to use the `expose` option in Docker Compose (works the same as `EXPOSE` in the Dockerfile) to allow other services to connect.

```
expose:
    - "1306"
```

You can also modify the default `EXPOSE 3306` to `EXPOSE 1306` in the `mysql` Dockerfile.

Following either of the above instructions, you should be able to connect to MySQL from the `workspace` using port `1306`.

That being said you might also need to change the port to which the instance of MySQL binds within the `mysql` container (if it doesn't listen to all the open ports), I sadly can't help you there since I haven't had to change the default `mysql port`.

**Comment by markdev** [comment]
@philtrep Thanks for the prompt response!

I've made all the changes, but the problem persists.  Here's the current configuration:

.env:
```
DB_CONNECTION=prod
DB_HOST=mysql
DB_PORT=1306
```

mysql/Dockerfile
```
FROM mysql:latest
MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>
ADD my.cnf /etc/mysql/conf.d/my.cnf
CMD ["mysqld"]
EXPOSE 1306
```

docker-compose.yml
```
    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        environment:
            MYSQL_DATABASE: laradock
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        expose:
            - "1306"
        ports:
            - "1306:1306"
# also tried this with "1306:3306"
        restart: always
```

Same thing; if `DB_PORT` in .env is 3306 it works; otherwise no dice.

When I run `docker-compose ps`, I see this for the mysql container:
````
laradock_mysql_1            docker-entrypoint.sh mysqld   Up       0.0.0.0:1306->1306/tcp, 3306/tcp   ```

If I `grep` for 3306 in the laradock directory, I can't find anything.  Is there something in the base image that forces it to set up on 3306?
