### ISSUE TITLE
bash: npm: command not found (fix included)

### ISSUE THREAD

**Issue by nicobrinkkemper** [laradock/laradock#427]
Hello! 

I'm having trouble using npm inside workspace container.

Here's what I type in: 

`laradock@53b3a82a9d29:/var/www$ nvm
bash: nvm: command not found`

`laradock@53b3a82a9d29:/var/www$ npm
bash: npm: command not found`

And here's the relevant part of my `docker-compose.yml`:

```
workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=true
                - INSTALL_NODE=true
                - INSTALL_YARN=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=true
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
                - TZ=UTC
```

I'm using windows 10 currently.

**FIX**
After building the workspace `docker-compose build workspace` I ran `docker-compose up -d nginx mysql redis` again to fix the issue. This should be included in the documentation, I think. Any thoughts?

Regards,

Nico
