### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by asolopovas** [laradock/laradock#443]
Hi, I am running laradock on Windows 10 Pro,  can't get it two work as laravel throws PDO exception in the browser but works fine in tinker. I tried changing .env to localhost and 127.0.0.1 get the same result, as well in config database file.  

This is the cmd I used to compose my container.
docker-compose up -d nginx mariadb redis php-fpm

**Comment by manshoor** [comment]
@asolopovas 
change your db host to mysql

`DB_CONNECTION=mysql`
`DB_HOST=mysql`

**Comment by asolopovas** [comment]
@manshoor it has been changed since I hose using vagrant with homestead.

**Comment by asolopovas** [comment]
@manshoor if I change DB_HOST to mysql thats what happens 
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by manshoor** [comment]
@asolopovas 
can you share your whole mysql settings in .env file.

because i'm on branch 4.12.0 and my config is this.

try `root` for username and password.

`DB_CONNECTION=mysql`
`DB_HOST=mysql`
`DB_PORT=3306`
`DB_DATABASE=mydbname`
`DB_USERNAME=root`
`DB_PASSWORD=root`

**Comment by manshoor** [comment]
well, i'm not sure about your side but default settings are working fine for me, i'm just using root credentials because i'm not using homestead db and too lazy to create a new user every time ;)

well your application is working 💯 now, so you're good to go.

**Comment by manshoor** [comment]
@philtrep we can close this issue.

**Comment by philtrep** [comment]
@manshoor Good job 👍

**Comment by marto-k** [comment]
How do you change Host to mysql.I did that and a big funny error appears in my konsole

[PDOException]                                                                                  
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known  
                                                                                                  

                                                                                               
  [PDOException]                                                                               
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by marto-k** [comment]
By the way all solutions i''ve tried none works for php artisan migrate.Over six hours of search and try nothing.If anyone got a solution sugestion please help me out

**Comment by marto-k** [comment]
![screenshot_20170223_000848](https://cloud.githubusercontent.com/assets/13986651/23232484/72c759ce-f95c-11e6-96e8-4b33ac6ddfba.png)

**Comment by asolopovas** [comment]
I figured out what was the problem. Simply you need edit your local hosts file to redirect host  that you specify in docker-compose.yml to 127.0.0.1, for example 
```
    // in this case the host is mariadb
    mariadb:
        build: ./mariadb
        volumes:
            - mariadb:/var/lib/mysql
            - ./mariadb/sql:/docker-entrypoint-initdb.d
            - ./mariadb/hosts:/var/tmp/hosts
        environment:
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - lemp-network
```

So your local hosts file will have this line.
`127.0.0.1 mariadb`

Then in your .env file put `DB_HOST=mariadb`

After that your artisan and webapp will be capable of successfully connecting to your docker db...
