### ISSUE TITLE
Connection with 'xdebug 2.4.1' was not established. 

### ISSUE THREAD

**Issue by gfd6th** [laradock/laradock#460]
I followed the guide of xdebug for phpstorm step by step.
But got the following issue.
`Connection with 'xdebug 2.4.1' was not established`

I'm not sure if I have configured correctly.
In the host, I add some host in `etc/hosts`

```
127.0.0.1       laravel
172.18.0.1      dockerhost
```

In the `docker-compose.yml`

```
### workspace contaner

extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.18.0.1"


### php-fpm container

 extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.18.0.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG=serverName=laravel

```
![image](https://cloud.githubusercontent.com/assets/6814715/20754867/d6b5a168-b747-11e6-9e48-4b9332b4fdb3.png)

I have configured the ssh, so I could ssh with the command `ssh -p2222 root@laravel`, and success visit `http://laravel/` in host browser.

phpunit worked fine, but failed when debug.

```bash
sftp://root@laravel:2222/usr/bin/php \ 
  -dzend_extension=/usr/lib/php/20151012/xdebug.so\
  -dxdebug.remote_enable=1 \
  -dxdebug.remote_mode=req \
  -dxdebug.remote_port=9000 \
  -dxdebug.remote_host=172.18.0.1 
  /var/www/laravel53/vendor/phpunit/phpunit/phpunit \
  --configuration /var/www/laravel53/phpunit.xml ExampleTest \ 
  /var/www/laravel53/tests/ExampleTest.php --teamcity

```

![image](https://cloud.githubusercontent.com/assets/6814715/20755053/89c4e7e6-b748-11e6-8ac3-9ae8644990ce.png)

I noticed that it is php7.0.9 in php-fpm container, but we actually using the php7.0.12 cli in workspace.
