### ISSUE TITLE
Where is Node / NPM?

### ISSUE THREAD

**Issue by mikeerickson** [laradock/laradock#468]
I have activated Node and NVM (as well as Yarn) in the docker-compose.yml.  Trying to figure out how to SSH to this container?

```
    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=false
                - INSTALL_NODE=true
                - INSTALL_YARN=true
```
