### ISSUE TITLE
Class 'Memcached' not found

### ISSUE THREAD

**Issue by mohammedibrahim** [laradock/laradock#492]
I followed the steps to run laravel but I got this error:

I checked the workspace and I can see memcahed installed in cli but when I checked the phpinfo from browser Its not installed.

![screenshot from 2016-12-16 13-27-10](https://cloud.githubusercontent.com/assets/1190075/21261408/d5e038ea-c393-11e6-8354-25b6f571d38e.png)

**Comment by jaydubbyasee** [comment]
@mohammedibrahim If you haven't already solved this already. You need to enable memcached for php-fpm as shown below:

```
 php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_SOAP=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_BCMATH=false
                - INSTALL_MEMCACHED=true
                - INSTALL_OPCACHE=false
                - INSTALL_AEROSPIKE_EXTENSION=false
```
