### ISSUE TITLE
Apache2 container Text file busy: AH00649: could not open transfer log file /docker.stdout.

### ISSUE THREAD

**Issue by sc10n** [laradock/laradock#505]
I am trying to run an nginx and apache container (nginx serving as the reverse proxy). I have been unable to run apache, though the container continues to run, when I attach to the logs it is spamming this:

```
apache2_1         | 2016-12-21 16:27:35,381 INFO spawned: 'apached' with pid 13130
apache2_1         | Replacing "<DOCUMENT_INDEX>" with "index.php" (case sensitive) (partial words matched)
apache2_1         | 2016-12-21 16:27:35,433 INFO success: apached entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
apache2_1         | Replacing "<DOCUMENT_ROOT>" with "/var/www/public" (case sensitive) (partial words matched)
apache2_1         | Replacing "<ALIAS_DOMAIN>" with "*.vm" (case sensitive) (partial words matched)
apache2_1         | Replacing "<SERVERNAME>" with "cbba0b2115ea" (case sensitive) (partial words matched)
apache2_1         | Replacing "<PHP_SOCKET>" with "php-fpm:9000" (case sensitive) (partial words matched)
apache2_1         | [Wed Dec 21 16:27:35.699660 2016] [log_config:error] [pid 13130:tid 140111026444160] (26)Text file busy: AH00649: could not open transfer log file /docker.stdout.
apache2_1         | AH00015: Unable to open logs
apache2_1         | 2016-12-21 16:27:35,712 INFO exited: apached (exit status 1; not expected)
```
The Apache section of the compose file looks like this.
```
    apache2:
        build:
            context: ./apache2
            args:
                - PHP_SOCKET=php-fpm:9000
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/apache2:/var/log/apache2
        ports:
           - "3000:80"
        links:
            - php-fpm
            - nginx
```
