### ISSUE TITLE
Upgrade Docker to 1.12.5 on mac - mysql Data is not loaded

### ISSUE THREAD

**Issue by iannazzi** [laradock/laradock#517]
I have been using laradock for almost a year with no issues. I upgraded docker to version 1.12.5. My databases are now empty. I see files are in ./data/mysql. Not sure why they are not loaded

here is my docker compose file - pretty standard. Let me know what else I can provide.

```
version: '2'

services:

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_NODE=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=false
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        ports:
           - "22:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
                - INSTALL_AEROSPIKE_EXTENSION=false
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "89:80"
            - "449:443"
        links:
            - php-fpm


### HHVM Container ##########################################

    hhvm:
        build: ./hhvm
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace

### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes:
            - ./mysql/startup:/docker-entrypoint-initdb.d
        volumes_from:
            - volumes_data
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234



### Caddy Server Container ##################################

    caddy:
        build: ./caddy
        volumes_from:
            - volumes_source
            - volumes_data
        ports:
            - "88:80"
            - "448:443"
            - "2018:2015"
        volumes:
            - ./caddy/Caddyfile:/etc/Caddyfile
            - ./logs/caddy:/var/log/caddy
        links:
            - php-fpm



### Laravel Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ../:/var/www/laravel
            # - ../vue:/var/www/vue
            # Demonstration of how to mount multiple sites

            # - ../../site_a/:/var/www/site_a
            # - ../../site_b/:/var/www/site_b

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/postgres:/var/lib/postgresql/data
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/neo4j:/var/lib/neo4j/data
            - ./data/mongo:/data/db
            - ./data/aerospike:/opt/aerospike/data
            - ./data/sessions:/sessions
            - ./data/caddy:/root/.caddy
            - ./data/elasticsearch/data:/usr/share/elasticsearch/data

### Add more Containers below ###############################
```
