### ISSUE TITLE
Multiple sites (Run many laravel projects)

### ISSUE THREAD

**Issue by luis-don-dev** [laradock/laradock#54]
I have recently switched from Laravel Homestead to Laradock and it is awesome, but I can't figure out how to create multiple sites and add phpmyadmin. Has someone achieved it? Thanks in advance.

**Comment by Mahmoudz** [comment]
The easiest way is to create multiple virtual machines if you are on mac or windows. Not really sure about any other ways to it!

However it's still doable but you have to change some ports, to do this:

Rename the `laradock` folder (where laradock is cloned) and run `docker-compose up -d ....` your new containers. 

If you have `projectA` and `projectB` you have can rename the laradock folder to `laradock_projectA` and `laradock_projectB`.

Now if you run `docker-compose up -d MySQL` this will create a container named `laradock_projectA_MySQL` and if your run the command from the other project it will create `laradock_projectB_MySQL`. 

The only problem you will be facing is Ports already in use. so edit the `docker-compose.yml` and change the ports.

If you found an easier way to do this in the future, please share it.

**Comment by tristanbailey** [comment]
Sounds like two issues. 
To run multiple sites you add the laradock folder to each project, you can then start each project in turn. 
There is an issue like noted above, that you would need to stop one project and then start the next as they take over the ports (I am sure there is a solution with this) 
The second one is if you want to install phpmyadmin, you would need to just put that in the project directory or in the Dockerfile to install in one of the containers. I would think if you put it inside your project you could configure it to work when it loaded

**Comment by ellisio** [comment]
I forked this for work and have an implementation of this working. What I did is merge `application` and `workspace` into one Dockerfile. This allows me to create multiple `app-{project-name}` containers. 

All projects are stored in `./apps/` relative to LaraDock's root.

## `docker-compose.yml` Configuration

Just find `app-projectA` in this configuration and add more projects like `app-projectB`.

```
version: '2'
services:
  # Applications...
  app-projectA:
    tty: true
    build: ./containers/app-projectA
    volumes:
      - ./apps/projectA:/var/www/app-projectA

  # Services...
  php-fpm:
    build:
        context: ./containers/php-fpm
        dockerfile: Dockerfile
    volumes_from:
      - app-projectA

  nginx:
    build: ./containers/nginx
    volumes_from:
      - app-projectA
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

  mariadb:
    build: ./containers/mariadb
    volumes_from:
      - data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: projectA
      MYSQL_USER: laradock
      MYSQL_PASSWORD: laradock
      MYSQL_ROOT_PASSWORD: root
    links:
      - php-fpm

  redis:
    build: ./containers/redis
    volumes_from:
      - data
    ports:
      - "6379:6379"
    links:
      - php-fpm

  beanstalkd:
    build: ./containers/beanstalkd
    ports:
      - "11300:11300"
    privileged: true
    links:
      - php-fpm

  beanstalkd-console:
    build: ./containers/beanstalkd-console
    ports:
      - "2080:80"
    environment:
      - "BEANSTALK_SERVERS=beanstalkd:11300"
    links:
      - beanstalkd

  # Data Container...
  data:
    build: ./containers/data
    volumes:
      - /var/lib/mariadb
      - /var/lib/redis
```

## Nginx Configuration

Now the bigger thing is you also have to modify the Nginx container. These are our configuration files for Nginx:

`Dockerfile`:
```
FROM nginx:latest
MAINTAINER Andrew Ellis <awellis89@gmail.com>

RUN mkdir -p /etc/nginx/certs

ADD nginx.conf /etc/nginx/
ADD fastcgi_params.conf /etc/nginx/
ADD app.conf /etc/nginx/

ADD apps/projectA.conf /etc/nginx/conf.d/
ADD apps/star.dev.projectA.com.cert /etc/nginx/certs/
ADD apps/star.dev.projectA.com.key /etc/nginx/certs/

RUN usermod -u 1000 www-data

EXPOSE 80 443

CMD ["nginx"]
```

`nginx.conf`:
```
user                      www-data;
worker_processes          1;
error_log                 /var/log/nginx/error.log  info;
pid                       /run/nginx.pid;
daemon                    off;

events {
  worker_connections      1024;
  multi_accept            on;
  use                     epoll;
}

http {
  include                 /etc/nginx/fastcgi_params.conf;
  include                 /etc/nginx/mime.types;
  default_type            application/octet-stream;
  set_real_ip_from        127.0.0.1;
  real_ip_header          X-Forwarded-For;
  charset                 utf-8;

  proxy_redirect          off;
  proxy_set_header        Host  $host;
  proxy_set_header        X-Real-IP $remote_addr;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  client_max_body_size    10m;
  client_body_buffer_size 128k;
  proxy_buffers           32 4k;
  fastcgi_send_timeout    60s;
  fastcgi_read_timeout    1d;

  gzip                    on;
  gzip_types              text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_disable            "MSIE [1-6]\.";
  gzip_static             on;

  tcp_nodelay             on;
  tcp_nopush              on;
  keepalive_timeout       65;
  sendfile                off;

  types_hash_max_size     2048;
  server_names_hash_bucket_size 64;

  include                 /etc/nginx/conf.d/*.conf;
}
```

`fastcgi_params.conf`:
```
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

fastcgi_param  HTTPS              $https;
```

`app.conf`:
```
## Deny dot files:
location ~ /\. {
  deny all;
}

## PHP
location ~ \.php$ {
  include       /etc/nginx/fastcgi_params.conf;
  fastcgi_pass  php-fpm:9000;
  fastcgi_index index.php;
}
```

`apps/projectA.conf`:
```
server {
  include             /etc/nginx/app.conf;

  listen              443 ssl;
  server_name         *.dev.projectA.com;

  access_log          off;
  error_log           /var/log/nginx/error.log;

  root                /var/www/app-projectA/public;
  index               index.php index.html;

  ssl                 on;
  ssl_certificate     /etc/nginx/certs/star.dev.projectA.com.cert;
  ssl_certificate_key /etc/nginx/certs/star.dev.projectA.com.key;
  ssl_protocols       SSLv3 TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers         ALL:!aNULL:!ADH:!eNULL:!LOW:!EXP:RC4+RSA:+HIGH:+MEDIUM;

  # Application Routes
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }
}
```

## MySQL Configuration

Unfortunately at this time I only know how to create one database, which is fine for our stack, but not for others using one set of containers for multiple projects locally. There's talk about a `VOLUME` and running a `.sh` script on ENTRYPOINT to create your schemas. But I haven't dug too far into it.

## Project Dockerfile

With what I mentioned above. The `workspace` container went away. We now have a per-project Dockerfile that looks like the following and lives in `./containers/app-projectA/Dockerfile`:

```
FROM phusion/baseimage:latest
MAINTAINER Andrew Ellis <awellis89@gmail.com>

RUN DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm

# Install "software-properties-common" (for the "add-apt-repository")
RUN apt-get update && apt-get install -y software-properties-common curl python-dev build-essential g++ unzip

# Install NodeJS Repo
RUN curl -s -L https://deb.nodesource.com/setup_5.x | sudo bash -

# Add the "PHP 7" ppa
RUN add-apt-repository -y ppa:ondrej/php

# Install PHP-CLI 7, some PHP extentions and some useful Tools with APT
RUN apt-get update && apt-get install -y \
        php7.0-cli \
        php7.0-common \
        php7.0-curl \
        php7.0-json \
        php7.0-xml \
        php7.0-mbstring \
        php7.0-mcrypt \
        php7.0-mysql \
        php7.0-zip \
        git \
        curl \
        vim \
        nano \
        nodejs

# Clean up, to free some space
RUN apt-get clean

# Install gulp with NPM
RUN npm install -g gulp

# Add an alias for PHPUnit
RUN echo "alias phpunit='./vendor/bin/phpunit'" >> ~/.bashrc

# Install Composer
RUN curl -s http://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

# Install Ngrok2
RUN curl -s -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip \
    && unzip ngrok-stable-linux-amd64.zip \
    && mv ngrok /usr/local/bin/ \
    && rm -f ngrok-stable-linux-amd64.zip

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/app-projectA
```

## Conclusion

Hopefully this helps the package maintainer make this a possibility.
