### ISSUE TITLE
How can I change the Postgres database name and user name?

### ISSUE THREAD

**Issue by hughgrigg** [laradock/laradock#542]
I'm trying to change the Laradock Postgres database name and user name, but without success.

I've changed the Postgres section of `docker-compose.yml` to look like this:

```yaml
### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: foobarname
            POSTGRES_USER: foobarname
            POSTGRES_PASSWORD: secret
```

I've since rebuilt the container and tried destroying all the images and building again from scratch. The Postgres database and username are still called `homestead`.

How can I configure this?
