### ISSUE TITLE
[FEATURE] Provide support for installing global node modules

### ISSUE THREAD

**Issue by mikeerickson** [laradock/laradock#553]
I don't see any interface to installing `node_modules` during `docker-compose up` action.  

I am thinking these can be added to the `docker-compose.yml` something like the following:

```
    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_NODE=true
        tty: true
        node_modules:
          - karma
          - mocha
          - gulp
```

All the modules will be installed if the INSTALL_NODE flag is true.

If you are interested in having this added, i will take care of it and submit a new PR accordingly
