### ISSUE TITLE
Elixir/Mix with Browsersync

### ISSUE THREAD

**Issue by cjmaxik** [laradock/laradock#640]
So, I finally managed to have Browsersync working with my Laravel Elixir setup. It only have one problem, so I want to share this settings with you and try to make a perfect solution for Laradock.

_This settings are for Elixir, but you can make it works on Mix (Laravel >= 5.4)_

gulpfile.js
```javascript
[...]
    mix.browserSync({
        proxy: '172.19.0.7', // nginx or caddy Docker ip (more on that later)
        host: 'project1.dev', // your hostname from .hosts
        open: false // there is no browser in workspace
    });
[...]
```
You will need to find caddy/nginx Docker IP. I simply bash'ed into caddy instance and executed `ifconfig`.

Last thing to do is open workspace ports to make Browsersync working:
```yaml
[...]
        ports:
            - "3000:3000"
            - "3001:3001"
[...]
```

So, only problem is this caddy/nginx Docker IP. IDK if it is static or dynamic about each stop/up sequence. If you have some thoughts, please share.

**Comment by philtrep** [comment]
@cjmaxik Great! Try using the hostnames `nginx` and `caddy`.

**Comment by cjmaxik** [comment]
@philtrep BINGO! It works. Thanks, totally forgot about that.

**Comment by Harti** [comment]
Like so?
Doesn't work for me.
```
mix.browserSync({
    proxy: 'nginx',
    host: 'project.dev',
    notify: false
});
```
I believe I've tried any permutation of proxy and host using localhost, nginx and project.dev. No dice. Would have been nice if you included a working config.

**Comment by Harti** [comment]
@philtrep 
@cjmaxik 
Could you please elaborate or point me to a solution? I'm stuck...

**Comment by ChaiMinChun** [comment]
The steps are:
1) Modify your webpack file
`mix.browserSync({
proxy:'172.17.0.1' //my docker ip
,open:false
});`

2) Modify your docker-compose.yml
After that add in "3000:3000" and "3001:3001" ports which is under workspace container section
![image](https://user-images.githubusercontent.com/10117740/32617961-635a6eb4-c5b1-11e7-8de6-db639f7f1255.png)

And you are good to go

**Comment by Harti** [comment]
@ChaiMinChun I can't thank you enough, it works! 

For future readers:
I used the 10.0.75.1 as the proxy IP address, it's the one I found in my Docker for Windows settings as well as in the `laradock/.env` file (`DOCKER_HOST_IP=10.0.75.1`).

**Comment by benplain** [comment]
I have tried this and can't get it to work.

Here is my docker-compose.yml modifications:
```
ports:
        - "${WORKSPACE_SSH_PORT}:22"
        - "3000:3000"
        - "3001:3001"
```

and here is what is in my webpack.mix.js
```
mix.browserSync({
    proxy: '10.0.75.1', // DOCKER_HOST_IP from .env
    port: 3000,
    open: false
});
```

When I run ```npm run watch``` it shows this:
```
[Browsersync] Proxying: http://10.0.75.1
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3002
    External: http://192.168.1.100:3002
 --------------------------------------
          UI: http://localhost:3003
 UI External: http://192.168.1.100:3003
 --------------------------------------
[Browsersync] Watching files...
```

Any ideas?

**Comment by Harti** [comment]
I actually realized that above configurations only work for some specific project setups. When using it in a Laravel project, it works just fine. When using it in an OctoberCMS project, however, it has the same issues that I previously reported.

I figure it may have to do with the folder you call `npm run watch` from, but didn’t come to a solution yet either. 
Adding the BrowserSync script to my layout file (`<script async type="text/javascript" src="//localhost:3000/browser-sync/browser-sync-client.js"></script> `) worked, although I’d say this isn’t the cleanest solution.

**Comment by mattquest** [comment]
For anyone with multiple virtual hosts that's stuck on this.  You might need to set whichever site you're currently working on as the "default_server" in your site .conf file.  It appears the server_name passed through in the request is "localhost" so it may not trigger your desired site to load.

**Comment by fdb19** [comment]
Just wanted to confirm that '172.17.0.1' is the correct proxy and not the ip found in the .env file (10.0.75.1).
172.17.0.1 is the default ip listed using **ifconfig docker0**.

**Comment by kulbon** [comment]
I've tried many combinations and this one worked for me:
in gulpfile.js
`gulp.task("browser-sync", function () {
    browserSync.init({
        proxy: '172.20.0.5',
        port: 3000,
	open:false
    });
});`

in docker-compose.yml

`workspace:
     ports:
        - "${WORKSPACE_SSH_PORT}:22"
        - "3000:3000"`

proxy: '172.20.0.5' This IP is taken from laradock container nginx IP adress

Works like a charm.

**Comment by DavidTrujillo** [comment]
> So, I finally managed to have Browsersync working with my Laravel Elixir setup. It only have one problem, so I want to share this settings with you and try to make a perfect solution for Laradock.
> 
> _This settings are for Elixir, but you can make it works on Mix (Laravel >= 5.4)_
> 
> gulpfile.js
> 
> ```js
> [...]
>     mix.browserSync({
>         proxy: '172.19.0.7', // nginx or caddy Docker ip (more on that later)
>         host: 'project1.dev', // your hostname from .hosts
>         open: false // there is no browser in workspace
>     });
> [...]
> ```
> 
> You will need to find caddy/nginx Docker IP. I simply bash'ed into caddy instance and executed `ifconfig`.
> 
> Last thing to do is open workspace ports to make Browsersync working:
> 
> ```yaml
> [...]
>         ports:
>             - "3000:3000"
>             - "3001:3001"
> [...]
> ```
> 
> So, only problem is this caddy/nginx Docker IP. IDK if it is static or dynamic about each stop/up sequence. If you have some thoughts, please share.

It failed me even when in proxy I put nginx.
It gave me 404.
I solved it with entering docker-compose exec workspace bash
And modify / etc / hosts
And put
[Ip from nginx] [my hostname]

**Comment by DavidTrujillo** [comment]
There is another way to do it, in the file docker-compose.yml put in nginx (in my case) section :

>    networks:
        frontend:
        backend:
          aliases:
            - mysitea
            - mysiteb

**Comment by freeyland** [comment]
Hi @Harti , did you find an other solution in the end for octobercms? (I know it is a long time ago :) )

**Comment by Harti** [comment]
@freeyland no, sorry. I put up with the manual script injection. I checked for environment variables‘ presence/absence to detect whether or not to render the script tag, as far as I can remember.

**Comment by Joseph7451797** [comment]
Here is my solution.

Workspace setting in `docker-compose.yml`:
```
[...]
  ports:
    - "3000:3000"
    - "3001:3001"
  links:
    - "nginx:mylocalsite.test"
[...]
```

Browsersync setting:
```js
{
  // use existing Nginx virtual host
  proxy: {
      target: 'https://mylocalsite.test/'
  },
  host: 'mylocalsite.test',
  open: false,
  // Disable it because I use browsersync's default port
  // port: 7777,
}
```

Remember to set up `Nginx` to ensure that `mylocalsite.test` can be resolved.
Reference: [Docker compose links](https://docs.docker.com/compose/compose-file/#links)

**Comment by freeyland** [comment]
Hi @Joseph7451797 

I've added  - "nginx:birdboard.test" in the links section of docker-compose.yml:
However when trying to start laradock, I get following error message:
docker-compose up -d nginx mysql phpmyadmin
ERROR: Circular dependency between nginx and docker-in-docker and php-fpm and workspace

**Comment by Joseph7451797** [comment]
Hi @freeyland, I apologize for the lack of pre-defined environment information.

In my use case, I copied lots settings in Laradock and moved them to my own project.
My `docker-compose.yml` is customized and modified, and here is the setting:
```
version: '3'

services:

### Workspace Utilities ##################################
    workspace:
      build:
        context: ./workspace
        args:
          - PHP_VERSION=${PHP_VERSION}
          - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
          - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
          - NODE_VERSION=${WORKSPACE_NODE_VERSION}
          - INSTALL_BOWER=${WORKSPACE_INSTALL_BOWER}
          - INSTALL_YARN=${WORKSPACE_INSTALL_YARN}
          - YARN_VERSION=${WORKSPACE_YARN_VERSION}
          - INSTALL_GULP=${WORKSPACE_INSTALL_GULP}
          - INSTALL_ANGULAR_CLI=${WORKSPACE_INSTALL_ANGULAR_CLI}
          - INSTALL_VUE_CLI=${WORKSPACE_INSTALL_VUE_CLI}
          - INSTALL_DUSK_DEPS=${WORKSPACE_INSTALL_DUSK_DEPS}
          - CHROME_DRIVER_VERSION=${WORKSPACE_CHROME_DRIVER_VERSION}
          - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ../:/var/www:cached
      ports:
        - "3000:3000"
        - "3001:3001"
      links:
        # https://docs.docker.com/compose/compose-file/#links
        - "nginx:mylocalsite.test"
### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=php-fpm
          - PHP_UPSTREAM_PORT=9000
      volumes:
        - ../:/var/www:cached
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/ssl/:/etc/nginx/ssl
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php-fpm

### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./php-fpm
        args:
          - DOCKER_HOST_IP=${DOCKER_HOST_IP}
          - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
      volumes:
          - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
          - ../:/var/www:cached

### Redis ################################################
    redis:
      build: ./redis
      volumes:
        - ./data/redis:/data
      ports:
        - "6379:6379"

### Memcached ############################################
    memcached:
      build: ./memcached
      volumes:
        - ./data/memcached:/var/lib/memcached
      ports:
        - "11211:11211"

[...]

```

`env` file:
```
PHP_VERSION=7.1

# local IP of host machine 
DOCKER_HOST_IP=your_machine_local_IP

### WORKSPACE #############################################

WORKSPACE_INSTALL_XDEBUG=true
WORKSPACE_INSTALL_NODE=true
WORKSPACE_NODE_VERSION=8
WORKSPACE_INSTALL_BOWER=false
WORKSPACE_INSTALL_YARN=true
WORKSPACE_YARN_VERSION=latest
WORKSPACE_INSTALL_GULP=false
WORKSPACE_INSTALL_ANGULAR_CLI=false
WORKSPACE_INSTALL_VUE_CLI=false
WORKSPACE_CHROME_DRIVER_VERSION=2.42
WORKSPACE_INSTALL_DUSK_DEPS=true
WORKSPACE_TIMEZONE=Asia/Taipei
```
Two things to be clarify:
1. Starting script: `docker-compose up -d workspace redis`
2. This setup is same as Laradock multiple projects setup. Reference: https://laradock.io/getting-started/#B

**Comment by tvercruysse** [comment]
> Here is my solution.
> 
> Workspace setting in `docker-compose.yml`:
> 
> ```
> [...]
>   ports:
>     - "3000:3000"
>     - "3001:3001"
>   links:
>     - "nginx:mylocalsite.test"
> [...]
> ```
> 
> Browsersync setting:
> 
> ```js
> {
>   // use existing Nginx virtual host
>   proxy: {
>       target: 'https://mylocalsite.test/'
>   },
>   host: 'mylocalsite.test',
>   open: false,
>   // Disable it because I use browsersync's default port
>   // port: 7777,
> }
> ```
> 
> Remember to set up `Nginx` to ensure that `mylocalsite.test` can be resolved.
> Reference: [Docker compose links](https://docs.docker.com/compose/compose-file/#links)

the `links: ...` did the trick, thanks @Joseph7451797 !

**Comment by Hexor** [comment]
Chinese version answer:

给中文读者的解答:

你能访问到 BrowserSync 的 JS 脚本，但是却访问不到项目。原因如下

你应该是在 workspace 这个 docker 内运行的 npm run watch 吧。

所以你在本机上通过3001接口能正常访问到 workspace 内运行的 browsersync。

但是如果 workpace docker不经过配置，在 workpace 内是无法访问到你的 nginx 站点的，因为你的项目配置在 nginx docker 内。这两个 docker 没有打通。

比如你可以尝试进入 workspace 的 bash，然后 curl 你的站点 url，应该是什么都访问不到。

解决方案就是让 workspace 和 nginx 互相打通：
1. 修改docker-compose.yml 中 workspace 的配置
```
      ports:
        - "3000:3000"
        - "3001:3001"
        - "${WORKSPACE_SSH_PORT}:22"
      tty: true
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2375
      networks:
        - frontend
        - backend
      links:
        - docker-in-docker
        - nginx:abc.xx.locahost(你的nginx站点）
```

2. 重新build workspace docker， 
```
docker-compose up -d --force-recreate --no-deps --build workspace
```

> 如果提示依赖出现问题，就修改 docker-composer.yml 中 nginx 的设置，把下面这个依赖删除， 然后重新 build
      depends_on:
        - php-fpm


3. laravel 项目的 webpack.mix.js 中的 browser-sync 代码写成
```mix.browserSync('abc.xx.locahost');```
4. 最后在 workspace 中的 laravel 项目中运行``` npm run watch```
5. 浏览器访问``` localhost:3000 ```
