### ISSUE TITLE
Solving error in mariadb environment

### ISSUE THREAD

**Issue by zeroc0d3** [laradock/laradock#656]
Hi @Mahmoudz,

Need some fix in docker-compose.yml file for mariadb
After i running : 
```
docker-compose up -d nginx mariadb phpmyadmin
```
I got this error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mariadb.environment contains an invalid type, it should be an object, or an array
```

So, the problem solved by adding some **dash** ("-") sign in environment:
**Before:**
```
mariadb:
        build: ./mariadb
        volumes:
            - mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
```
**After:**
```
mariadb:
        build: ./mariadb
        volumes:
            - mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE: homestead
            - MYSQL_USER: homestead
            - MYSQL_PASSWORD: secret
            - MYSQL_ROOT_PASSWORD: root
```
