### ISSUE TITLE
Multiple postgres containers: no pg_hba.conf entry for host

### ISSUE THREAD

**Issue by brezzhnev** [laradock/laradock#692]
Hi,
I need to create a test database for my application, I duplicated PostgreSQL container:
```
### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123

### PostgreSQL Container for test purposes ##################

    postgres-test:
        build: ./postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5435:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
```

I can enter to psql on port *5435* within host machine:
```
psql -h localhost -p 5435 -U postgres -d postgres
```
But when I trying to execute psql with *5434* I get following error:
```
psql: FATAL:  no pg_hba.conf entry for host "172.22.0.1", user "postgres", database "postgres", SSL off
```

Within guest machine I get same error:
```
docker-compose exec --user=laradock workspace bash
psql -h postgres -U postgres -d postgres
```

I'm a beginner in docker and I stuck here, please, help me.

**Comment by zeroc0d3** [comment]
In your `postgres-test`:
```
 ports:
     - "5435:5432"
```
could you change & test it (with different port?):
``` 
ports:
      - "5435:5433"
```

**Comment by brezzhnev** [comment]
@zeroc0d3 thanks for your response. I tried to change port and it works within guest machine, but when I trying to connect from host machine using `psql -h localhost -p 5435 -U postgres -d postgres` it returns following:
```
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
Same connection to psql with port *5434* works fine. In really I find strange to use different local ports in containers...

**Comment by zeroc0d3** [comment]
Could you test this (change all ports):
```
postgres:
  ports:
  - "5434:5434"
```
and
```
postgres-test:
  ports:
  - "5435:5435"
```
When you need to connect by terminal outside docker container:
```
docker ps
```
Find the IP Address of your postgres & postgres-test container:
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' [container_id]
```
Then use:
```
psql -h [ip_container] -p 5432 -U postgres -d postgres
```
We use "default" port connection 5432

**Comment by alchimik** [comment]
@brezzhnev Why use two containers if they use the shared volume (postgres)?

I think you should use two volums:
```
### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

### PostgreSQL Container ####################################

    postgres-test:
        build: ./postgres
        volumes:
            - postgres-test:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

...

### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
    postgres:
        driver: "local"
    postgres-test:
        driver: "local"
```
