### ISSUE TITLE
Make LaraDock framework agnostic

### ISSUE THREAD

**Issue by Mahmoudz** [LaraDock/laradock#76]
Let LaraDock be used by any PHP developer, not only Laravel developers. 

By default it should be configured to run any PHP at a general directory `www/` and then depend on your framework, you should do a little modification (Nginx configuration..) to make it work.

Start by supporting: Symfony, CakePHP, Yii, Codeigniter, Slim, Lumen, Zend and of course Laravel. Then we'll cover other frameworks.

**Comment by mattythebatty** [comment]
I'd actually started doing something like this just to test it out on a few projects (WordPress, OpenCart and Arastta) and was going to publish them as separate repositories in an [organisation](https://github.com/DockerIt). 

I've put a simple (WordPress Docker)[https://github.com/DockerIt/wordpress-docker] one there. I went for separate repositories for each projects for a couple of reasons
- the dependencies on different frameworks/projects might be different and need more than just a different nginx config file (e.g. gd, imageick, mbstring etc)
- it might make sense to put the docker files in a certain folder
- other framework users might find it easier to contribute
- making a change work change it on all frameworks

**Comment by Mahmoudz** [comment]
Hi @mattythebatty what you are saying is true, however I'm against multiple repositories because maintaining multiple repositories is a bit harder for me and for all the other contributions, especially because the difference between all the repositories will not exceed the 30%.

I have few ideas in mind but I'm open to hear the community solutions, for keeping single project supporting all frameworks by something like defining the framework name in the `.yml` file.

One more thing regarding your suggestion I'm not considering Wordpress in that Feature I'm only looking for PHP framework (at least for now). So your project is very nice and helpful for Wordpress users.

**Comment by psampaz** [comment]
This would be a great feature! 
:+1:

**Comment by ojhaujjwal** [comment]
I like how @Mahmoudz  said it for handling multiple frameworks by defining framework name in .yml file.
```
    workspace:
        build:
            context: ./workspace
            args:
                - PROJECT_TYPE=laravel # or drupal or magento

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - PROJECT_TYPE=laravel
```
Then,  in `Dockerfile`,  we can install php extensions according to PROJECT_TYPE variable
