### ISSUE TITLE
'error' => 'Could not resolve host: elasticsearch', 'errno' => 6

### ISSUE THREAD

**Issue by nugrahawahyu** [laradock/laradock#807]
I cant seed my searchable model from php db:seed, but when i create new model from the form i got "'error' => 'Could not resolve host: elasticsearch', 'errno' => 6" error. any idea how to fix this?

**Comment by bestlong** [comment]
@nugrahawahyu Need more information.

what are you run **docker-compoe** full command?

or show you run **docker-compoe ps** command result.

**Comment by nugrahawahyu** [comment]
@bestlong this my command "docker-compose up -d nginx php-fpm workspace mysql elasticsearch redis"

**Comment by bestlong** [comment]
@nugrahawahyu Edit docker-compose.yml and add **-backend** to elasticsearch networks node:

```
### ElasticSearch Container #################################

    elasticsearch:
      build: ./elasticsearch
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
        - elasticsearch-plugins:/usr/share/elasticsearch/plugins
      ports:
        - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
        - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend
```
then stop containers, build elasticsearch service and start containers.
