### ISSUE TITLE
How to connect database with my own project with laradock?

### ISSUE THREAD

**Issue by at-tienpham** [laradock/laradock#816]
Hi all,
I have 1 issue need any help from everyone. I use laradock is server for my own project. I install package Phinx via composer. But when i run migrate i have error
```
root@8c2c8404426f:/var/www# vendor/bin/phinx migrate
Phinx by Rob Morgan - https://phinx.org. 0.8.0

using config file ./phinx.yml
using config parser yaml
using migration paths 
 - /var/www/db/migrations
using seed paths 
 - /var/www/db/seeds
warning no environment specified, defaulting to: development
using adapter mysql
using database default

                                                                                                    
  [InvalidArgumentException]                                                                        
  There was a problem connecting to the database: SQLSTATE[HY000] [2002] No such file or directory
```
i config .env laradock
```
### MYSQL Container
MYSQL_DATABASE=default
MYSQL_USER=root
MYSQL_PASSWORD=root
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
```
and phinx.yml
```
paths:
    migrations: %%PHINX_CONFIG_DIR%%/db/migrations
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds

environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: mysql
        host: localhost
        name: production_db
        user: root
        pass: ''
        port: 3306
        charset: utf8

    development:
        adapter: mysql
        host: localhost
        name: default
        user: root
        pass: root
        port: 3306
        charset: utf8

    testing:
        adapter: mysql
        host: localhost
        name: testing_db
        user: root
        pass: ''
        port: 3306
        charset: utf8

version_order: creation
```
This is my structure folder my own project
```
-app
-data
----myqsl
-db
----migrations
-laradock
-public
----index.php
-vendor
conposer.json
phinx.yml
```
Thanks for help

**Comment by zeroc0d3** [comment]
@at-tienpham, you can't use "localhost" for your mysql container. You need to define the IP address from docker container.

Check your container IP Address:
`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' [container_id]`

Use "mysql" container IP Address in your definition host

**Comment by at-tienpham** [comment]
@zeroc0d3 sorry. mysql container not use "localhost", file .env have not MYSQL_HOST? Are you talk about phinx.yml?

**Comment by zeroc0d3** [comment]
@at-tienpham, yes thats right in your phink.yml file.. no need to change your .env laradock file.

**Comment by at-tienpham** [comment]
@zeroc0d3 After get IP address is 172.20.0.2 from id container abf4dbe396b5. I change config 
```
paths:
    migrations: %%PHINX_CONFIG_DIR%%/db/migrations
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds

environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: mysql
        host: localhost
        name: production_db
        user: root
        pass: ''
        port: 3306
        charset: utf8

    development:
        adapter: mysql
        host: 172.20.0.2
        name: default
        user: root
        pass: root
        port: 3306
        charset: utf8

    testing:
        adapter: mysql
        host: localhost
        name: testing_db
        user: root
        pass: ''
        port: 3306
        charset: utf8

version_order: creation
```
But it's not work. First time is : '172.20.0.2' and second times is : 172.20.0.2 . But not ok.
