### ISSUE TITLE
Cannot get php-worker container to work

### ISSUE THREAD

**Issue by sefaYavuz** [laradock/laradock#835]
I get an error when i put this code in my docker-compose.yml file:

```yml
php-worker:
      build:
        context: ./php-fpm
        dockerfile: Dockerfile-70 # or Dockerfile-56, choose your PHP-FPM container setting
      volumes_from:
        - applications
      command: php artisan queue:work
```
And the error i get:

```sh
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/sqlsrv.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/sqlsrv.so: cannot open shared object file: No such file or directory in Unknown on line 0

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/pdo_sqlsrv.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

It seems it cannot load the extensions sqlsrv and pdo_sqlsrv. Anyone know how to fix this issue?
