### ISSUE TITLE
Postgres-postgis does not create database with name set in .env

### ISSUE THREAD

**Issue by jvzanatta** [laradock/laradock#900]
### Info:
- Docker version 17.03.1-ce, build c6d412e
- Laradock commit 15d7cd1d35d05dadbbe5b1a440de0f7e38059733 
- Ubuntu 16.04: 

### Issue:
I just tryed Laradock for the first time and it's great. But i have a problem with postgres and postgres-postgis container.
The `docker-compose up postgres` created a database named `default` as it was set in the `.env` file I cloned from `env-example`. After I eddited it to `teste_db`, I tried to run all the below commands to try to rerun the `"database creation"` script:

```
docker-compose up --build postgres
docker-compose up --build --force-recreate postgres
docker-compose up --force-recreate postgres
docker-compose build postgres ; docker-compose up postgres
```
None of that did it. I had to go to the /tmp/postgres folder and erase all its content in order to archieve what i needed.

Is there a better way to create a database?

_____

### Expected behavior:
I expected the database would have the name declared on the `.env` file, like below
`### POSTGRES ###########################################################################################################

POSTGRES_DB=teste_db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=secret
POSTGRES_PORT=5432`

**Comment by rasparac** [comment]
@jvzanatta did you make it work?

**Comment by jvzanatta** [comment]
@rasparac by deleting the generated /tmp/postgres file, yes. But not the way I intended to.

**Comment by bestlong** [comment]
data folder generate rule is follow parent Dockerfile

right now laradock default configuration is save it on Host os not in container,

please ref #952 #950 

if intended container create will initialized db, you can commented about DATA_SAVE_PATH volume set in docker-compose.yml like:

```
### MySQL Container #########################################

    mysql:
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        #- ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

### PostgreSQL Container ####################################

    postgres:
      build: ./postgres
      #volumes:
      #  - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend
```
