### ISSUE TITLE
PHP-Worker: No Memcached servers added.

### ISSUE THREAD

**Issue by xpert13** [laradock/laradock#934]
### Issue:
When I try to use **PHP-Worker** I got runtime error `No Memcached servers added.`

_____

### Fix:

To fix it You need to add `extra_hosts` to compose file:
```
### PHP Worker Container #####################################

    php-worker:
      build:
        context: ./php-worker
      volumes_from:
        - applications
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      networks:
        - backend
```
