### ISSUE TITLE
Laradock with both php 5.6 and 7.0

### ISSUE THREAD

**Issue by nickstable** [laradock/laradock#956]
Hello,

I'm trying to use a unique config for 2 projects using apache2 :
- project A uses php 5.6
- project B uses php 7.0

The setup of multiple projects with same php is simple and explained here http://laradock.io/#B. But with different php versions, should I add a second php-fpm with fixed php version in my docker-compose ? The documentation explains how to switch from php 7.0 to php 5.6, but help to add php 5.6 while keeping php 7.0 is welcome.

My containers :
- apache2:ubuntu
- php-fpm:7.0
- php-fpm:5.6
- mysql:latest
- postgres:latest

Laradock also add application and workspace containers. Should I add a second application and workspace container too ?

Otherwise i was thinking to use laradock just for the first project, and add a second docker-compose "hand-made" for second project, linking to laradock's docker-compose to access apache2 and databases.

Anyone face this before ?

**Comment by clenoma** [comment]
I found a custom-made docker-compose file to support 2 php version, the developper idea is to use ports 80 or 8070 for php7.0 and port 8056 for php5.6.

Also idea is to separate folders /var/www/php70/ and /var/www/php56/ for legacy support.

I would like to keep using laradock while having this choice. I will dig into this and publish something if I find a solution.

version: '2'
services:
  nginx:
    build: ./config/nginx/
    container_name: nginx
    volumes_from:
        - www_data
    links:
        - php-7.0
        - php-5.5
    ports:
      - 80:80

  php-7.0:
    build: ./config/7.0/
    container_name: php-7.0
    volumes_from:
        - www_data

  php-5.6:
    build: ./config/5.6/
    container_name: php-5.6
    volumes_from:
        - www_data

  www_data:
    image: tianon/true
    volumes:
      - .:/var/www/html

**Comment by aurawindsurfing** [comment]
Hi I wonder what solution did you end up using please?

**Comment by nunomazer** [comment]
I'm using an installation of Laradock, one for each version I want to work: `laradock-56`, `laradock-70`, etc. 

Then I have created bash scripts to execute the version I want, depending of the project I'm working on, so just run `dc-56-up`, so the script tries to shutdown all instances running and up the one I want

**Comment by Smittttty** [comment]
I needed php-fpm 7.0, and 5.6. I solved this the following way(using laradock multi project setup):

I copied the laradock/php-fpm folder and renamed it as php-fpm5.6,

In the docker-composer.yml I copied the entire php-fpm structure, and renamed the new one as php-fpm5.6, I then hardcoded the PHP_VERSION to 5.6 in the new structure. Under NGINX I also had to add php-fpm5.6 to the depends_on list.

Then in nginx conf(yourdomain.conf) for the site that needed php5.6, I modified `fastcgi_pass php-upstream;` value line to be `fastcgi_pass php-fpm5.6:9000;`

After doing that I did a `docker-compose down` followed up a `docker-compose up` and the site that needed php5.6 was now running on 5.6, while the other is running on 7.0.

**Comment by shijunti19** [comment]
I need it, and it's necessary！
The old system has the highest support for php5.6

**Comment by rodolfobubb** [comment]
@Smittttty worked for me! Thanksss!!

**Comment by laliux** [comment]
In fact is not necessary to copy all laradock/php-fpm folder. Adding a new entry in docker-compose.yml with the hardcoded PHP version is enough.

```
### PHP-FPM 7.0 ##############################################
    php-fpm-7.0:
      build:
        context: ./php-fpm
        args:
          - PHP_VERSION=7.0
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
          - INSTALL_PHPDBG=${PHP_FPM_INSTALL_PHPDBG}
          - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE}
...
```

**Comment by morales2k** [comment]
Indeed, it is exactly right as @laliux explains.

This worked for me and, in case it wasn't clear enough from @Smittttty and @laliux comments, here's some more detail and/or clarity... 

In the `docker-compose.yml` file, copy the php-fpm setup that comes with laradock into the following:
```
### PHP-FPM5.6 ##############################################
  php-fpm5.6:
    build:
      context: ./php-fpm
      args:
        - LARADOCK_PHP_VERSION=5.6
        {all other options(args) remain the same - redacted for space}
    volumes:
      - ./php-fpm/php5.6.ini:/usr/local/etc/php/php.ini
      {the rest remains the same as the original fpm config for laradock - redacted for space}
```

What this does is, it launches a hard-coded php-fpm5.6 container. You will no longer control php version for this container from the .env file, but the other options will still apply, so you can have the same set of extensions/args as available in the .env file for both versions of php_fpm (or more if you choose to go  and do this for every version of php available in laradock; sky's the limit! and by sky I mean your computer cpu and ram lol)

To use it on a project or a local website, just go to your laradock folder, look up the nginx/sites and check out the default.conf. It uses `fastcgi_pass` as follows: 
```
fastcgi_pass php-upstream;
```
Since what we got there in the upstream is another version of php (not 5.6) and we want to use 5.6 for this other project, we create the new site conf file and update that line to:
```
fastcgi_pass php-fpm5.6:9000;
``` 
That will tell nginx to use the other fpm service in the backend network.

This way, you can keep only one laradock location with all your container settings, use the correct php version for your project, and code away.

As mentioned elsewhere, if one needs to replicate remote environment (php version, extension set, nginx version, etc), it would be best to clone laradock right into the project folder and configure it all specifically for said project... instead of using a global - jack of all trades configuration, with all bells and whistles... However, for most small projects, this global configuration is quite flexible and suits most of the cases I work with, so I'll stick to this for now.

**Comment by igordelorenzi** [comment]
**An addition to @morales2k answer**

I missed one last step, which is add the new php-fpm-56 as dependency of nginx:

```
nginx:
      build:
        context: ./nginx
        args:
          ...
      volumes:
        ...
      ports:
        ...
      depends_on:
        - php-fpm
        - php-fpm-56
      networks:
        ...
```

**Comment by timmaybrown** [comment]
@igordelorenzi I think the simplest thing to make the workspace use the additional version of php would be to do the exact same solution as described by @morales2k and @laliux suggested for making an additional `php-fpm-56` service. 

Simply clone the `workspace` service definition, give it a new name, replace the `LARADOCK_PHP_VERSION` env variable with either a newly created env variable such as `LARADOCK_PHP_VERSION_ALT1` or place a static value in the `args` section of the new definition and then it will build a new `workspace-php56` container with packages that match the desired version of php.

```
 workspace-php56:
      build:
        context: ./workspace
        args:
          - LARADOCK_PHP_VERSION=5.6
...
```
