### ISSUE TITLE
After close docker-machine and container, the tables in database disappear.

### ISSUE THREAD

**Issue by BeeHuang** [LaraDock/laradock#96]
After close docker-machine and container, the tables in database disappear.

**Comment by appleboy** [comment]
You remove docker machine? or run `docker-compose down`?

**Comment by BeeHuang** [comment]
No, I  just run docker-machine stop.

**Comment by toonztudio** [comment]
I have the same problem too. I didn't down with docker-compose down. I just stop with docker-compose stop and ctrl + d to exit from bash. But after I restart my laptop everything lost.
Can anyone help ?

**Comment by toonztudio** [comment]
After my previous comment. I try to use docker-compose stop and then docker-machine stop.
And then try to start it again, my data is still alive!! 
I think I get it wrong I don't have to ctrl + d. just stop it.

**Comment by toonztudio** [comment]
I installed laradock on 2 environments 
    - digital ocean (docker 1.11.2 on ubuntu 14.04 droplet) 
    - and my labtop (mac osx el capitan, docker version 1.11.2, docker-composer version 1.7.1) 

On digital ocean after I stop with 'docker-compose stop' command then quit ssh terminal and login back to turn on droplet. everything is awesome. My data still alive. I found /var/lib/mysql file.

But when I back to check on my laptop. after I stop with 'docker-compose stop' and try to start with 'docker-compose start' again, everything was gone. no data and no /var/lib/mysql file.

Can anyone suggest me for this situation ?

**Comment by Belphemur** [comment]
You could try changing the binding of the volumes in the docker-composer.yml. For now, the script let docker manage the volumes. You can change this to ask docker to put in your host the data, it reduces the risk of losses.

```yml
    data:
        build: ./data
        volumes:
            - /data/mysql:/var/lib/mysql
            - /data/pgsql:/var/lib/postgresql
            - /data/maria:/var/lib/mariadb
            - /data/redis:/var/lib/redis
            - /data/memcached:/var/lib/memcached
            - /data/neo4j:/var/lib/neo4j/data
```

This should make the data folders available on your host at the path */data/SERVICE*
