### ISSUE TITLE
Use of fail2ban and remote client ip

### ISSUE THREAD

**Issue by vitoo** [laradock/laradock#961]
Hello,

I plan to use laradock for production, but i can't use fail2ban because nginx logs the docker IP in logs. (172.x.x.x).

I dont know if i can use the host network ? 

If somebody got an idea, thanks for your help!

**Comment by bestlong** [comment]
Hi @vitoo 
nginx log folder will mount to NGINX_HOST_LOG_PATH, is in .env set.
you can adjust the setting.

**Comment by vitoo** [comment]
That's not the problem, i have access of this log, but nginx logs the docker IP ex : 172.x.x.x and i want the remote client IP (internet ip address)

I think i have to set nginx, php-fpm & all service to host network 

ex : 


```yaml
    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM=php-fpm
      volumes_from:
        - applications
      volumes:
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      network_mode: host
 #     networks:
  #     - frontend
    #    - backend
```
