### ISSUE TITLE
How to Run Multiple Laravel Project?

### ISSUE THREAD

**Issue by codeitlikemiley** [laradock/laradock#977]
I have clone this repo...
copy .env
change the nginx conf...

here is my .env
```
APPLICATION="../homestead/,../laravel/"
```
Error is like this...
```
$ docker-compose up -d nginx mysql
ERROR: Named volume ""../homestead/,../laravel/":/var/www:rw" is used in service "applications" but no declaration was found in the volumes section.
```

How do you guys do Multiple Path of the Application?

Do i need to Redeclare APPLICATION?
like so
```
APPLICATION=../homestead/
APPLICATION=../laravel/
```

Hope someone can help me thanks

**Comment by bestlong** [comment]
Hi @codeitlikemiley 

```
// folder structure
+ laradock
+ phpshop
  + public
+ phpcrm
  + public
+ nonlaravelapp
  - index.php
```

```
// file .env
APPLICATION=../
```

```
cp nginx/sites/project-1.conf.example nginx/sites/phpshop.conf
cp nginx/sites/project-1.conf.example nginx/sites/phpcrm.conf
cp nginx/sites/project-1.conf.example nginx/sites/nonlaravelapp.conf
```

```
// edit phpshop.conf
server {
    listen 80;
    listen [::]:80;

    server_name phpshop.dev;
    root /var/www/phpshop/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
```

```
// edit phpcrm.conf
server {
    listen 80;
    listen [::]:80;

    server_name phpcrm.dev;
    root /var/www/phpcrm/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
```

```
// edit nonlaravelapp.conf
server {
    listen 80;
    listen [::]:80;

    server_name nonlaravelapp.dev;
    root /var/www/nonlaravelapp;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
```

```
// edit host os /etc/hosts and add IP/Hostname mapping
127.0.0.1  phpshop.dev
127.0.0.1  phpcrm.dev
127.0.0.1  nonlaravelapp.dev
```

**Comment by faphdev** [comment]
Hello, thanks for the detailed explanation. I followed your instruction but I am getting 403 forbidden from Nginx. What are the changes needed for docker-compose.yml file?

**Comment by manshoor** [comment]
have you checked nginx logs?

**Comment by Grald** [comment]
the same problem here @faphdev. Did you fix yours?

**Comment by Grald** [comment]
Thanks @bestlong

**Comment by agcty** [comment]
I have a similar problem, however, I want my apps living on the same domain but just in different folders.

My config looks like this:

```yaml
//.env
# Point to the path of your applications code on your host
APP_CODE_PATH_HOST=../frontend/dist/
API_CODE_PATH_HOST=../laravel-api/

# Point to where the `APP_CODE_PATH_HOST` should be in the container. You may add flags to the path `:cached`, `:delegated`. When using Docker Sync add `:nocopy`
APP_CODE_PATH_CONTAINER=/var/www/frontend/:cached
API_CODE_PATH_CONTAINER=/var/www/api/:cached
```

```yaml
//docker-compose.yml
### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - CHANGE_SOURCE=${CHANGE_SOURCE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${API_CODE_PATH_HOST}:${API_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
```

```nginx
//nginx.conf
server {

    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/frontend/;
    server_name localhost;
    index index.php index.html index.htm;

    location / {
        alias /var/www/frontend/;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /laravel {
        alias /var/www/api/public/;
        try_files $uri $uri/ @laravel;
        # try_files $uri $uri/ /index.php$is_args$args;

        location ~ \.php$ {
            fastcgi_pass php-upstream;
            fastcgi_index index.php;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            #fixes timeouts
            fastcgi_read_timeout 600;
            include fastcgi_params;
        }
    }

    location @laravel {
        rewrite /laravel/(.*)$ /laravel/index.php?/$1 last;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
```

I always get this error message: `nginx_1 | 2018/10/21 11:15:00 [error] 8#8: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.112.1, server: localhost, request: "GET /laravel/api/dddd HTTP/1.1", upstream: "fastcgi://192.168.112.5:9000", host: "localhost"`
Any help would be appreciated!
