### ISSUE TITLE
Connection refused tcp://127.0.0.1:6379

### ISSUE THREAD

**Issue by Zabanya** [laradock/laradock#986]
### Info:
- Docker version (`$ docker --version`): Docker version 17.03.1-ce, build c6d412e
- Laradock commit (`$ git rev-parse HEAD`): f296a39bf5b6a449dc833d36a36c880aa95169d1
- System info (Mac, PC, Linux): Win 10
- System info disto/version: 

##### What seems to be going wrong?

start laravel with nginx mysql and redis

ConnectionException in AbstractConnection.php line 155: 
Connection refused [tcp://127.0.0.1:6379]

i can ssh to redis container, command redis-server would return
Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
Creating Server TCP listening socket *:6379: bind: Address already in use

_____

##### What should be happening instead?

_____

##### How might we be able to reproduce the error?

_____

### Relevant Code:

```
// place code here
```

**Comment by Zabanya** [comment]
after hours of googling finally know that i need to add docker name / hostname to etc/host before using it :(

**Comment by SamoilenkoEvgeniy** [comment]
If someone also received such a problem, this is explanation:

https://stackoverflow.com/questions/42360356/docker-redis-connection-refused

**Comment by jasperf** [comment]
What I also had once is that horizon was already running and when I tried a `art horizon` I got a `Connection refused [tcp://127.0.0.1:6379]` or `Connection refused [tcp://redis:6379]` . Then I realized going to site.test/horizon got things running.

**Comment by ryancwalsh** [comment]
I'm running my Docker in production, so I want good security, so I tried to follow https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-18-04, which says that `bind 127.0.0.1 ::1` is important.

But I was getting multiple `Predis\Connection\ConnectionException, Code: 111: Connection refused [tcp://redis:6379]` errors per second.

Then I rebuilt my Redis container with `bind 0.0.0.0`, and I think it works.

But then I understood from https://stackoverflow.com/a/39314221/470749 and https://serverfault.com/a/619505/119666 that `bind 0.0.0.0` is unsafe too.

This is my workaround for now:

`docker inspect laradock_redis_1 | grep "IPAddress"` showed me that my Redis IP is 172.20.0.4.

So I added `bind 172.20.0.4` into `vim /apps/laradock/redis/redis.conf`.

Then I rebuilt: `cd /apps/laradock/ && docker-compose build --no-cache redis`.

And recreated: `cd /apps/laradock && docker-compose up -d nginx mysql redis php-worker`.

I think it seems to be working now. 

@jasperf  @SamoilenkoEvgeniy @Mahmoudz 

**However, my concern is that I've also seen the IP be 172.20.0.3. How can I specify a static IP that I can rely on? I don't want my config to fail just because I took a container down and restarted it, for example.** 

Thanks.

**Comment by jasperf** [comment]
@ryancwalsh I have not gone all the way to production as I had issues with Redis as mentioned. Curious in general on your setup so if you could share it in a repo that would be great. I have [one](https://github.com/jasperf/laravel-docker-development), but am calling it local for now until it has been improved.
As for static ips, did you try working with an altered or new network instead of just frontend or backend as it is? [SO thread here](https://stackoverflow.com/questions/27937185/assign-static-ip-to-docker-container#35359185) talks about it using something like
```
version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx-container
    networks:
      static-network:
        ipv4_address: 172.20.128.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24
```
Someone needed it for Nginx and wrote about it in [this Laradock issue too](https://github.com/laradock/laradock/issues/705). He used
```
networks:

    static-network:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: "${SUBNET}"
              gateway: "${GATEWAY_IP}"
```
in `docker-compose.yaml`. This for a new network and then in his Nginx Docker file he added
```
networks:
        - static-network
        - default
```
